/**
 * Caregiver scheduling — shared types + helpers.
 *
 * A schedule entry assigns ONE caregiver to a GROUP of residents for a single
 * date + shift (AM / PM / NOC). Stored migration-free as an app-setting JSON
 * array under `caregiver_schedules` (see the Prisma-migration constraint).
 *
 * Phase 1 (this file + CaregiverScheduleBoard) only reads/writes the roster.
 * Phase 2's server-side access lock (tenant.ts) reuses `activeResidentIdsFor`
 * to resolve which residents a caregiver may see *right now* — so the shift
 * window logic lives here, in one place, shared by client and server.
 */

export const CAREGIVER_SCHEDULE_KEY = "caregiver_schedules";
/** Break-glass grants are hidden from the client (`__` prefix — the generic
 *  /api/db route filters those out) and written only by the dedicated endpoint. */
export const CAREGIVER_BREAKGLASS_KEY = "__caregiver_breakglass";

export type ShiftKey = "AM" | "PM" | "NOC";

/** Assignable shifts. Windows mirror TaskAssignmentBoard: AM 6a–2p, PM 2p–10p,
 *  Noc 10p–6a (spills into the next calendar day). */
export const SHIFTS: ReadonlyArray<{
  key: ShiftKey; label: string; range: string; startH: number; endH: number; nextDay: boolean;
}> = [
  { key: "AM",  label: "AM Shift",  range: "6:00 – 14:00",  startH: 6,  endH: 14, nextDay: false },
  { key: "PM",  label: "PM Shift",  range: "14:00 – 22:00", startH: 14, endH: 22, nextDay: false },
  { key: "NOC", label: "Noc Shift", range: "22:00 – 6:00",  startH: 22, endH: 6,  nextDay: true  },
];

export const shiftMeta = (shift: ShiftKey) => SHIFTS.find((s) => s.key === shift) ?? SHIFTS[0];

/** Grace minutes the shift stays live PAST its end so a caregiver can finish late
 *  tasks and hand over. e.g. 60 → an AM (6–14) caregiver keeps their residents
 *  until 15:00. Extends only the end; the start is unchanged. */
export const SHIFT_GRACE_MINUTES = 60;

/** Lead-in minutes the shift goes live BEFORE its start so a caregiver who clocks
 *  in early sees their assignment and routine. e.g. 15 → a PM (14–22) caregiver
 *  reaches their residents from 13:45. Extends only the start; the end is unchanged. */
export const SHIFT_LEAD_MINUTES = 15;

export interface CaregiverSchedule {
  id: string;
  date: string;            // YYYY-MM-DD (local calendar date the shift starts)
  shift: ShiftKey;
  caregiverStaffId: string;
  caregiverUserId?: string; // resolved so the server lock can match by session userId
  caregiverName: string;
  residentIds: string[];              // the authority for access scoping
  /** Name/room snapshot taken at assign time so a caregiver sees resident names
   *  even for a future shift (their live resident reads are shift-scoped). */
  residents?: { id: string; name: string; room: string }[];
  note?: string;
  /** True when the roster cell represents dedicated/private caregiver coverage. */
  private?: boolean;
  /** Original roster code retained for accountable assignment review. */
  code?: string;
  /** "roster" when generated by the Staff Roster bridge (so a re-sync can replace
   *  its own entries without clobbering hand-made assignments). */
  source?: string;
  createdBy?: string;
  createdAt: string;
  updatedAt?: string;
  /** Explicit worker receipt of the current assignment version. */
  acknowledgedAt?: string;
  acknowledgedByUserId?: string;
  /** Incremented whenever a manager changes the assignment. */
  changeVersion?: number;
}

export function parseSchedules(raw: string | undefined | null): CaregiverSchedule[] {
  if (!raw) return [];
  try {
    const v = JSON.parse(raw);
    if (!Array.isArray(v)) return [];
    return v.filter((s): s is CaregiverSchedule =>
      !!s && typeof s.id === "string" && typeof s.date === "string" && Array.isArray(s.residentIds));
  } catch {
    return [];
  }
}

export function newScheduleId(): string {
  return `cs_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
}

/** Milliseconds `timeZone` is ahead of UTC at the given instant (DST-aware). */
function zoneOffsetMs(at: Date, timeZone: string): number {
  try {
    const parts = new Intl.DateTimeFormat("en-GB", {
      timeZone, year: "numeric", month: "2-digit", day: "2-digit",
      hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false,
    }).formatToParts(at);
    const get = (type: string) => Number(parts.find((p) => p.type === type)?.value);
    const asUtc = Date.UTC(get("year"), get("month") - 1, get("day"), get("hour") % 24, get("minute"), get("second"));
    return Number.isFinite(asUtc) ? asUtc - at.getTime() : 0;
  } catch {
    return 0;
  }
}

/**
 * A facility wall-clock time (`YYYY-MM-DD` + hour) as the TRUE instant it happens.
 *
 * Without this, `new Date(y, m, d, 6)` means 06:00 *on the server*, which on a UTC
 * host is 14:00 in Manila — so every comparison against a stored timestamp lands a
 * whole shift away. Pass no `timeZone` to keep the old server-local behaviour.
 */
export function zonedInstant(date: string, hour: number, timeZone?: string): Date {
  const [y, mo, d] = date.split("-").map(Number);
  if (!timeZone) return new Date(y, (mo || 1) - 1, d || 1, hour, 0, 0, 0);
  const naive = Date.UTC(y, (mo || 1) - 1, d || 1, hour, 0, 0, 0);
  // Sample the offset at the guessed instant, then re-sample at the corrected one so
  // a wall time sitting on a DST boundary still resolves to the right instant.
  const first = naive - zoneOffsetMs(new Date(naive), timeZone);
  return new Date(naive - zoneOffsetMs(new Date(first), timeZone));
}

/** Instant range [start, end) a schedule's shift occupies in the facility's zone. */
export function shiftWindow(date: string, shift: ShiftKey, timeZone?: string): { start: Date; end: Date } {
  const m = shiftMeta(shift);
  return {
    start: zonedInstant(date, m.startH, timeZone),
    end: zonedInstant(addDays(date, m.nextDay ? 1 : 0), m.endH, timeZone),
  };
}

/**
 * The shift a moment belongs to, as the roster records it: which AM/PM/NOC key, the
 * calendar date the shift STARTED on (a NOC shift read at 01:00 belongs to yesterday's
 * roster row), and the true instant window. One resolver so the dashboard read model
 * and its metric drill-downs cannot drift apart.
 */
export function resolveShift(at: Date = new Date(), timeZone?: string): {
  key: ShiftKey; date: string; start: Date; end: Date;
} {
  const key = currentShiftKey(at, timeZone);
  const day = localDateStr(at, timeZone);
  const date = key === "NOC" && localMinutesOfDay(at, timeZone) < shiftMeta("NOC").endH * 60
    ? addDays(day, -1)
    : day;
  return { key, date, ...shiftWindow(date, key, timeZone) };
}

/** Roster rows covering a resolved shift — the authority for "who is covered now". */
export function schedulesForShift(
  schedules: CaregiverSchedule[], shift: { date: string; key: ShiftKey },
): CaregiverSchedule[] {
  return schedules.filter((s) => s.date === shift.date && s.shift === shift.key);
}

/**
 * True when `at` falls inside the schedule's SHIFT WINDOW (facility-local).
 *
 * Access is shift-scoped: a caregiver reaches their assigned residents only
 * while the rostered shift is live. The moment the shift ends the residents drop
 * off (an AM caregiver loses them at 14:00) and reappear only when the nurse /
 * care manager rosters them a shift whose window is currently active. Off every
 * rostered window → they see nothing until rescheduled.
 *
 * Compared in facility-local time (hour + calendar date), never as server-local
 * Date objects, so a UTC server still evaluates the window in the facility's zone.
 */
export function isScheduleActiveAt(s: CaregiverSchedule, at: Date, timeZone?: string): boolean {
  const day = localDateStr(at, timeZone);
  const nowMin = localMinutesOfDay(at, timeZone);
  const m = shiftMeta(s.shift);
  const startMin = m.startH * 60 - SHIFT_LEAD_MINUTES; // lead-in opens the shift early
  const endMin = m.endH * 60 + SHIFT_GRACE_MINUTES;    // grace extends the shift end
  const DAY = 24 * 60;
  if (!m.nextDay) {
    // AM (06–14) / PM (14–22): same calendar day. Grace may push the end past
    // midnight, spilling the overflow into the next calendar day's early hours.
    if (s.date === day && nowMin >= startMin && nowMin < Math.min(endMin, DAY)) return true;
    return endMin > DAY && day === addDays(s.date, 1) && nowMin < endMin - DAY;
  }
  // NOC (22–06 +grace) spans midnight: the 22:00–23:59 part belongs to s.date;
  // the 00:00–(06:00+grace) part belongs to the day AFTER s.date.
  if (s.date === day && nowMin >= startMin) return true;
  return day === addDays(s.date, 1) && nowMin < endMin;
}

/**
 * Resident ids a caregiver (by session userId) is assigned to AND currently
 * on-shift for at `at`. This is the authority for the server access boundary.
 * `timeZone` (IANA, e.g. "Asia/Manila") evaluates the shift window in the
 * facility's local time — the server may run in UTC.
 */
export function activeResidentIdsFor(userId: string, schedules: CaregiverSchedule[], at: Date, timeZone?: string): string[] {
  const ids = new Set<string>();
  for (const s of schedules) {
    if (s.caregiverUserId && s.caregiverUserId === userId && isScheduleActiveAt(s, at, timeZone)) {
      s.residentIds.forEach((r) => ids.add(r));
    }
  }
  return [...ids];
}

/**
 * Caregiver userIds whose LIVE shift covers `residentId` at `at` — the people who
 * can currently see/chart that resident's tasks (shift-window scoped, incl. NOC
 * after midnight + grace). Empty when no one is on an active shift for them.
 * Used to route a due-task alert to exactly the caregiver on duty right now.
 */
export function activeCaregiverUserIdsForResident(residentId: string, schedules: CaregiverSchedule[], at: Date, timeZone?: string): string[] {
  const ids = new Set<string>();
  for (const s of schedules) {
    if (s.caregiverUserId && s.residentIds.includes(residentId) && isScheduleActiveAt(s, at, timeZone)) {
      ids.add(s.caregiverUserId);
    }
  }
  return [...ids];
}

/** The AM/PM/NOC shift `at` falls in (AM 06–14, PM 14–22, else NOC), rolled
 *  forward by {@link SHIFT_LEAD_MINUTES} so the last minutes before a shift start
 *  already report the incoming shift (13:50 → PM). */
export function currentShiftKey(at: Date = new Date(), timeZone?: string): ShiftKey {
  const min = (localMinutesOfDay(at, timeZone) + SHIFT_LEAD_MINUTES) % (24 * 60);
  if (min >= 6 * 60 && min < 14 * 60) return "AM";
  if (min >= 14 * 60 && min < 22 * 60) return "PM";
  return "NOC";
}

/** Caregivers scheduled to a resident on the local day of `at` (any shift). */
export function caregiversForResidentToday(
  schedules: CaregiverSchedule[], residentId: string, at: Date = new Date(), timeZone?: string,
): { caregiverStaffId: string; caregiverUserId?: string; caregiverName?: string; shift: ShiftKey }[] {
  const today = localDateStr(at, timeZone);
  return schedules
    .filter((s) => s.date === today && s.residentIds.includes(residentId) && s.caregiverStaffId)
    .map((s) => ({ caregiverStaffId: s.caregiverStaffId, caregiverUserId: s.caregiverUserId, caregiverName: s.caregiverName, shift: s.shift }));
}

/**
 * Best single assignee for a resident's generated tasks today: the caregiver on
 * the CURRENT shift, else the first caregiver scheduled today, else null (leave
 * the task unassigned). Used to route generated tasks straight to the caregiver
 * who is covering the resident.
 */
export function assigneeForResidentToday(
  schedules: CaregiverSchedule[], residentId: string, at: Date = new Date(), timeZone?: string,
): { caregiverStaffId: string; caregiverName?: string } | null {
  const list = caregiversForResidentToday(schedules, residentId, at, timeZone);
  if (!list.length) return null;
  const cur = currentShiftKey(at, timeZone);
  const pick = list.find((c) => c.shift === cur) ?? list[0];
  return { caregiverStaffId: pick.caregiverStaffId, caregiverName: pick.caregiverName };
}

/**
 * The caregiver rostered for a resident on a SPECIFIC shift today, or null when
 * that shift has no coverage. Unlike {@link assigneeForResidentToday} (which
 * collapses the day to one caregiver), this routes each frequency occurrence to
 * the caregiver actually on duty for that occurrence's shift — so a twice-daily
 * task lands on the AM caregiver and the PM caregiver separately.
 */
export function assigneeForResidentShift(
  schedules: CaregiverSchedule[], residentId: string, shift: ShiftKey, at: Date = new Date(), timeZone?: string,
): { caregiverStaffId: string; caregiverName?: string } | null {
  const pick = caregiversForResidentToday(schedules, residentId, at, timeZone).find((c) => c.shift === shift);
  return pick ? { caregiverStaffId: pick.caregiverStaffId, caregiverName: pick.caregiverName } : null;
}

// ── Break-glass (emergency off-assignment access) ─────────────────────────────
export interface BreakGlassGrant {
  id: string;
  caregiverUserId: string;
  caregiverName?: string;
  residentId: string;
  residentName?: string;
  reason: string;
  at: string;         // ISO granted-at
  expiresAt: string;  // ISO — end of the shift the grant was opened in
}

export function parseBreakglass(raw: string | undefined | null): BreakGlassGrant[] {
  if (!raw) return [];
  try {
    const v = JSON.parse(raw);
    if (!Array.isArray(v)) return [];
    return v.filter((g): g is BreakGlassGrant =>
      !!g && typeof g.caregiverUserId === "string" && typeof g.residentId === "string" && typeof g.expiresAt === "string");
  } catch {
    return [];
  }
}

/** Resident ids a caregiver has an UNEXPIRED break-glass grant for at `at`. */
export function activeBreakglassResidentIds(userId: string, grants: BreakGlassGrant[], at: Date): string[] {
  const ids = new Set<string>();
  for (const g of grants) {
    if (g.caregiverUserId === userId && new Date(g.expiresAt) > at) ids.add(g.residentId);
  }
  return [...ids];
}

/** End of the local calendar day `at` — a break-glass grant lives until then
 *  (matches the whole-day access model). */
export function endOfDay(at: Date): Date {
  const d = new Date(at);
  d.setHours(23, 59, 59, 999);
  return d;
}

/** End of the shift window `at` falls in (kept for reference / shift math). */
export function currentShiftEnd(at: Date): Date {
  const h = at.getHours();
  const d = new Date(at);
  if (h >= 6 && h < 14) { d.setHours(14, 0, 0, 0); return d; }   // AM → 14:00
  if (h >= 14 && h < 22) { d.setHours(22, 0, 0, 0); return d; }  // PM → 22:00
  if (h >= 22) { d.setDate(d.getDate() + 1); d.setHours(6, 0, 0, 0); return d; } // Noc → next 06:00
  d.setHours(6, 0, 0, 0); return d;                              // 0–5 → Noc end 06:00
}

// ── Local date helpers (calendar grid) ────────────────────────────────────────
const pad = (n: number) => String(n).padStart(2, "0");
export const toDateStr = (d: Date): string => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
export const todayStr = (): string => toDateStr(new Date());

/** Facility-local minutes-of-day (0–1439) of `at`. Server-local without a tz. */
export function localMinutesOfDay(at: Date, timeZone?: string): number {
  if (!timeZone) return at.getHours() * 60 + at.getMinutes();
  try {
    const parts = new Intl.DateTimeFormat("en-GB", { timeZone, hour: "2-digit", minute: "2-digit", hour12: false }).formatToParts(at);
    const h = Number(parts.find((p) => p.type === "hour")?.value) % 24;
    const mi = Number(parts.find((p) => p.type === "minute")?.value);
    return (Number.isFinite(h) ? h : 0) * 60 + (Number.isFinite(mi) ? mi : 0);
  } catch {
    return at.getHours() * 60 + at.getMinutes();
  }
}

/** YYYY-MM-DD `n` days after a calendar-date string (UTC math avoids tz drift). */
function addDays(dateStr: string, n: number): string {
  const [y, mo, d] = dateStr.split("-").map(Number);
  const dt = new Date(Date.UTC(y, (mo || 1) - 1, (d || 1) + n));
  return `${dt.getUTCFullYear()}-${pad(dt.getUTCMonth() + 1)}-${pad(dt.getUTCDate())}`;
}

/** YYYY-MM-DD for `at` in a given IANA time zone (falls back to server-local).
 *  en-CA formats as YYYY-MM-DD. Used server-side so "today" is the facility's
 *  calendar day, not the server's UTC day. */
export function localDateStr(at: Date, timeZone?: string): string {
  if (!timeZone) return toDateStr(at);
  try {
    return new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).format(at);
  } catch {
    return toDateStr(at);
  }
}
