import {
  Grid,
  Activity,
  Users,
  Settings,
  ShieldCheck,
  AlertTriangle,
  CheckCircle,
  Clock,
  MessageSquare,
  DollarSign,
  Palette,
  Sparkles,
  Building2,
  Stethoscope,
  Cross,
  Layers,
  HeartHandshake,
  UserRound,
  UserPlus,
  DoorOpen,
  BedDouble,
  Package,
  FileText,
  Pill,
  BellRing,
  Timer,
  ClipboardList,
  History,
  BookOpen,
  PenTool,
  Target,
  Bus,
  Ambulance,
  Car,
  Route,
  Wrench,
  Fuel,
  Utensils,
  Ticket,
  ConciergeBell,
  Repeat,
  CalendarDays,
  Siren,
  Syringe,
  FolderOpen,
  CalendarCheck,
  BarChart3,
  Shield,
  ClipboardCheck,
  Bell,
  LayoutDashboard,
  Gauge,
  Mail,
  ServerCog,
  CircleDollarSign,
  CreditCard,
  BadgeCheck,
  Receipt,
  Wallet,
  PieChart,
  TrendingDown,
  ShoppingCart,
  Camera,
  Scale,
  Video,
  HeartPulse,
  Accessibility,
  Bandage,
  ListTodo,
  ScrollText,
  Send,
  TrendingUp,
  NotebookPen,
  FileSignature,
  PhoneCall,
  Inbox,
  Fingerprint,
  MapPin,
} from "lucide-react";

export type Role =
  | "PLATFORM_ADMIN"
  | "ORGANIZATION_ADMIN"
  | "SUPERADMIN"
  | "FACILITY_ADMIN"
  | "CARE_MANAGER"
  | "RESIDENT_COORDINATOR"
  | "BILLING_ADMIN"
  | "PHYSICIAN"
  | "NURSE"
  | "CAREGIVER"
  | "FAMILY"
  | "RESIDENT"
  | "FLEET_MANAGEMENT"
  | "DRIVER"
  | "SECURITY"
  | "NUTRITIONIST"
  | "KITCHEN"
  | "HOUSEKEEPING"
  | "MAINTENANCE";

export interface SidebarLink {
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  route: string;
  /** Optional per-link sidebar group override (wins over the name-based map). */
  group?: SidebarGroup;
}

export interface RoleDetails {
  name: string;
  badge: string;
  desc: string;
  icon: React.ComponentType<{ className?: string }>;
  profileName: string;
  footerText: string;
  basePath: string;
  sidebarLinks: SidebarLink[];
  /** Role-specific primary navigation order from the Care360 role brief. */
  sidebarGroupOrder?: readonly SidebarGroup[];
}

export const ROUTE_TO_TAB: Record<string, string> = {
  dashboard: "Reporting & Care Intelligence",
  schedule: "Appointments & Activities",
  coordination: "Open Coordination",
  familycontacts: "Contacts & Update Preferences",
  endorsement: "Coordination Endorsement",
  monitoring: "Vitals Monitor",
  incidents: "Incident Log",
  records: "Resident Profile & Care Record",
  staff: "Staff Registry",
  tasks: "Daily Care Documentation & Monitoring",
  residents: "Resident Profile & Care Record",
  reports: "Shift Endorsement & Continuity",
  relative: "Monitoring",
  timeline: "Health Timeline",
  report: "Daily Care Documentation & Monitoring",
  alerts: "Alerts",
  alertcenter: "Alert Center",
  messages: "Messages",
  photos: "Photos",
  appointments: "Appointments",
  expenses: "Billing",
  goals: "Care Planning",
  admin: "Reporting & Care Intelligence",
  shift: "Reporting & Care Intelligence",
  family: "Reporting & Care Intelligence",
  appearance: "Landing Studio",
  assistant: "AI Assistant",
  matrix: "Portal Matrix",
  crm: "CRM & Leads",
  leads: "CRM & Leads",
  consentforms: "Consent & Move-in Forms",
  forms: "Sign & Upload",
  admissions: "Admissions & Registration",
  registration: "Admissions & Registration",
  prescreen: "Pre-Admission Assessment (v4.2)",
  assessmentv42: "Pre-Admission Assessment (v4.2)",
  todayscare: "Today's Care",
  additionalservices: "Additional Clinical Services",
  safeguarding: "Safeguarding",
  infectioncontrol: "Infection Control",
  emergencyprotocol: "Emergency & Evacuation",
  clinicalprotocols: "Clinical Protocols",
  rooms: "Rooms",
  occupancy: "Occupancy",
  billing: "Billing",
  ledger: "Transactions Ledger",
  receivables: "Receivables & Aging",
  revenue: "Revenue by Source",
  charges: "Service Charges",
  invoices: "Invoice Generation",
  payments: "Payment Processing",
  insurance: "Insurance Validation",
  receipts: "Receipts",
  onlinepayment: "Online Payment",
  inventory: "Inventory",
  purchaserequests: "Purchase Requests",
  medications: "Medication Management & Inventory",
  callbells: "Call Bells",
  timeclock: "Time Clock",
  rounds: "Assessment & Level of Care",
  casereview: "Assessment & Level of Care",
  careplans: "Care Planning",
  caredelivery: "Care Delivery",
  privatecare: "Private Caregivers",
  consults: "Consults & Referrals",
  escalations: "Sbar Escalation",
  orders: "Medication Management & Inventory",
  approvalworkflows: "Approvals",
  physiciancomms: "Physician Comms Log",
  referrals: "Referrals & Appointments",
  notes: "Clinical Notes",
  labs: "Labs & Allergies",
  vitals: "Vitals Trends",
  careteam: "Care Team",
  requests: "Transport Requests",
  ambulance: "Ambulance Booking",
  trips: "Trip Board",
  vehicles: "Vehicles",
  drivers: "Drivers",
  maintenance: "Maintenance",
  fuel: "Fuel & Odometer",
  transport: "Transport",
  dining: "Dining & Compliance",
  checklist: "Inspection Checklist",
  services: "Resident Services",
  concierge: "Concierge",
  frontdesk: "Front Desk",
  turnover: "Unit Turnover",
  community: "Community & Events",
  documentation: "Daily Care Documentation & Monitoring",
  vaccinations: "Vaccinations",
  documents: "Resident Documents",
  mar: "Medication Administration Record",
  medcompliance: "Medication Compliance",
  medinventory: "Medication Inventory",
  minipharmacy: "Mini Pharmacy",
  loccpricing: "Level of Care Pricing",
  residentbilling: "Resident Billing Records",
  followups: "Follow-up Tracker",
  auditlog: "Audit Log",
  "inventory-alerts": "Inventory Alerts",
  clinicalreports: "Clinical Reports",
  progressreport: "Resident Progress Report",
  appointmentcalendar: "Appointments Calendar",
  taskboard: "Task Assignment",
  taskassignment: "Task Assignment",
  caregiverschedule: "Caregiver Schedule",
  staffroster: "Staff Roster",
  securitylog: "Security & Incident Log",
  cameralogs: "Camera Activity Log",
  cameras: "Camera Registry",
  dietorders: "Diet & Nutrition Orders",
  kitchen: "Kitchen — Cook List",
  carelogs: "Care Logs",
  carehistory: "Care History",
  residentjourney: "One Care · One Journey",
  clinicalrecords: "Clinical Records",
  staffprofiles: "Staff Profiles & Records",
  clockin: "Time In · Clock In / Out",
  geofencing: "Geofencing",
  vitalstrend: "Vitals Trend",
  adlmonitoring: "ADL Monitoring",
  weightmonitoring: "Weight Monitoring",
  shiftsummary: "Shift Summary",
  careacuity: "Care Acuity & Level of Care",
  woundcare: "Wound Care",
  shiftendorsements: "Shift Endorsements",
  featurematrix: "SLMS Feature Matrix & System Overview",
  workspaces: "Customer Workspaces",
  plans: "Plans & Entitlements",
  usage: "Usage & Capacity",
  access: "Access",
  security: "Security & Audit",
  health: "System Health",
  platformsettings: "Platform Settings",
  communities: "Communities",
  people: "People & Access",
  approvals: "Pending Approvals",
  invitations: "Register Staff",
  subscription: "Usage & Subscription",
  branding: "Organization Branding",
  audit: "Organization Audit",
};

export const PATH_TO_ROLE: Record<string, Role> = {
  platform_admin: "PLATFORM_ADMIN",
  organization_admin: "ORGANIZATION_ADMIN",
  nurse: "NURSE",
  superadmin: "SUPERADMIN",
  caregiver: "CAREGIVER",
  family: "FAMILY",
  facility_admin: "FACILITY_ADMIN",
  care_manager: "CARE_MANAGER",
  resident_coordinator: "RESIDENT_COORDINATOR",
  billing_admin: "BILLING_ADMIN",
  physician: "PHYSICIAN",
  resident: "RESIDENT",
  fleet_management: "FLEET_MANAGEMENT",
  driver: "DRIVER",
  security: "SECURITY",
  nutritionist: "NUTRITIONIST",
  kitchen: "KITCHEN",
  housekeeping: "HOUSEKEEPING",
  maintenance: "MAINTENANCE",
};

export const ROLES: Record<Role, RoleDetails> = {
  PLATFORM_ADMIN: {
    name: "Platform Admin",
    badge: "Platform Admin",
    desc: "Provision and govern SaaS customer organizations, communities, plans, and subscriptions.",
    icon: ShieldCheck,
    profileName: "Platform Administrator",
    basePath: "/platform_admin",
    footerText: "Platform Admin Portal",
    sidebarLinks: [
      { name: "Overview", icon: LayoutDashboard, route: "/platform_admin/dashboard" },
      { name: "Customer Workspaces", icon: Building2, route: "/platform_admin/workspaces" },
      { name: "Plans & Entitlements", icon: BadgeCheck, route: "/platform_admin/plans" },
      { name: "Usage & Capacity", icon: Gauge, route: "/platform_admin/usage" },
      { name: "Access", icon: Users, route: "/platform_admin/access" },
      { name: "Security & Audit", icon: Shield, route: "/platform_admin/security" },
      { name: "System Health", icon: Activity, route: "/platform_admin/health" },
      { name: "Platform Settings", icon: ServerCog, route: "/platform_admin/platformsettings" },
    ],
  },
  ORGANIZATION_ADMIN: {
    name: "Organization Admin",
    badge: "Organization Admin",
    desc: "Manage company communities, people, invitations, access, subscription usage, and tenant configuration.",
    icon: Building2,
    profileName: "Organization Administrator",
    basePath: "/organization_admin",
    footerText: "Organization Admin Portal",
    sidebarLinks: [
      { name: "Organization Overview", icon: LayoutDashboard, route: "/organization_admin/dashboard" },
      { name: "Communities", icon: Building2, route: "/organization_admin/communities" },
      { name: "People & Access", icon: Users, route: "/organization_admin/people" },
      { name: "Pending Approvals", icon: ClipboardCheck, route: "/organization_admin/approvals" },
      { name: "Register Staff", icon: UserPlus, route: "/organization_admin/invitations" },
      { name: "Usage & Subscription", icon: Gauge, route: "/organization_admin/subscription" },
      { name: "Invoices", icon: FileText, route: "/organization_admin/invoices" },
      { name: "Organization Branding", icon: Palette, route: "/organization_admin/branding" },
      { name: "Organization Audit", icon: Shield, route: "/organization_admin/audit" },
    ],
  },
  SUPERADMIN: {
    name: "Administrator",
    badge: "Full System Access",
    desc: "Full system access — approvals, audit, staff registries, and system-wide oversight.",
    icon: Settings,
    profileName: "Administrator",
    basePath: "/superadmin",
    footerText: "Super Admin Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/superadmin/dashboard" },
      { name: "SLMS Feature Matrix", icon: ShieldCheck, route: "/superadmin/featurematrix" },
      { name: "Alert Center", icon: BellRing, route: "/superadmin/alertcenter", group: "Clinical Monitoring" },
      { name: "Daily Care Logs", icon: NotebookPen, route: "/superadmin/carelogs" },
      { name: "Camera Activity Log", icon: Activity, route: "/superadmin/cameralogs" },
      { name: "Camera Registry", icon: Camera, route: "/superadmin/cameras" },
      { name: "Geofencing", icon: MapPin, route: "/superadmin/geofencing", group: "Administration" },
      // "Portal Matrix" is merged into "SLMS Feature Matrix" as its Access Control tab.
      { name: "CRM & Leads", icon: UserPlus, route: "/superadmin/crm" },
      { name: "Consent & Move-in Forms", icon: ClipboardList, route: "/superadmin/consentforms" },
      { name: "Admissions & Registration", icon: UserPlus, route: "/superadmin/admissions" },
      { name: "Staff Registry", icon: Users, route: "/superadmin/staff" },
      { name: "Caregiver Schedule", icon: CalendarCheck, route: "/superadmin/caregiverschedule" },
      { name: "AI Assistant", icon: Sparkles, route: "/superadmin/assistant" },
      { name: "Landing Studio", icon: Palette, route: "/superadmin/appearance" },
      // Core SLMS Modules Aligned
      { name: "Residents", icon: Users, route: "/superadmin/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/superadmin/rounds" },
      { name: "Care Planning", icon: Target, route: "/superadmin/careplans" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/superadmin/tasks" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/superadmin/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/superadmin/medications" },
      { name: "Sbar Escalation", icon: Siren, route: "/superadmin/escalations" },
      { name: "Vaccinations", icon: Syringe, route: "/superadmin/vaccinations" },
      { name: "Resident Documents", icon: FolderOpen, route: "/superadmin/documents" },
      { name: "Medication Administration Record", icon: Pill, route: "/superadmin/mar" },
      { name: "Approvals", icon: ClipboardCheck, route: "/superadmin/approvalworkflows", group: "Medication" },
      { name: "Audit Log", icon: Shield, route: "/superadmin/auditlog" },
      { name: "Inventory Alerts", icon: Bell, route: "/superadmin/inventory-alerts" },
      { name: "Clinical Reports", icon: BarChart3, route: "/superadmin/clinicalreports" },
    ],
  },
  NURSE: {
    name: "Head Nurse",
    badge: "Clinical Care",
    desc: "Access real-time resident vitals, receive instant fall detection warnings, and log via Voice AI.",
    icon: Activity,
    profileName: "Sarah Jenkins, RN",
    basePath: "/nurse",
    footerText: "Nurse Clinical Portal",
    sidebarGroupOrder: ["Shift Command", "Clinical Triage Queue", "Caregiver Deployment", "Shift Watchlist", "Care Delivery Status", "Assessment & LOC", "Care Plan Governance", "Shift Endorsement"],
    sidebarLinks: [
      { name: "Shift Command", icon: LayoutDashboard, route: "/nurse/dashboard", group: "Shift Command" },
      { name: "Time In - Clock In / Out", icon: Fingerprint, route: "/nurse/clockin", group: "Shift Command" },
      { name: "Clinical Alerts", icon: BellRing, route: "/nurse/alertcenter", group: "Clinical Triage Queue" },
      { name: "Call Bells", icon: BellRing, route: "/nurse/callbells", group: "Clinical Triage Queue" },
      { name: "Nurse Review & Escalations", icon: Siren, route: "/nurse/escalations", group: "Clinical Triage Queue" },
      { name: "Incident Review", icon: AlertTriangle, route: "/nurse/incidents", group: "Clinical Triage Queue" },
      { name: "Caregiver Deployment", icon: ListTodo, route: "/nurse/taskassignment", group: "Caregiver Deployment" },
      { name: "Caregiver Schedule", icon: CalendarCheck, route: "/nurse/caregiverschedule", group: "Caregiver Deployment" },
      { name: "Staff Roster", icon: Users, route: "/nurse/staffroster", group: "Caregiver Deployment" },
      { name: "Resident Directory", icon: UserRound, route: "/nurse/residents", group: "Shift Watchlist" },
      { name: "One Care - One Journey", icon: Route, route: "/nurse/residentjourney", group: "Shift Watchlist" },
      { name: "Clinical Records", icon: FolderOpen, route: "/nurse/clinicalrecords", group: "Shift Watchlist" },
      { name: "Care Timeline", icon: History, route: "/nurse/carehistory", group: "Shift Watchlist" },
      { name: "Daily Care Logs", icon: NotebookPen, route: "/nurse/carelogs", group: "Shift Watchlist" },
      { name: "Daily Living (ADL)", icon: Accessibility, route: "/nurse/adlmonitoring", group: "Shift Watchlist" },
      { name: "Weight Tracking", icon: Scale, route: "/nurse/weightmonitoring", group: "Shift Watchlist" },
      { name: "Wound Care", icon: Bandage, route: "/nurse/woundcare", group: "Shift Watchlist" },
      { name: "Vital Sign Trends", icon: HeartPulse, route: "/nurse/vitalstrend", group: "Shift Watchlist" },
      { name: "Today's Approved Care", icon: CalendarCheck, route: "/nurse/todayscare", group: "Care Delivery Status" },
      { name: "Care Delivery", icon: Activity, route: "/nurse/caredelivery", group: "Care Delivery Status" },
      { name: "Medication Administration (MAR)", icon: Syringe, route: "/nurse/mar", group: "Care Delivery Status" },
      { name: "Medication Compliance", icon: PieChart, route: "/nurse/medcompliance", group: "Care Delivery Status" },
      { name: "Assessment & Level of Care", icon: Gauge, route: "/nurse/careacuity", group: "Assessment & LOC" },
      { name: "Pre-Admission Assessment (v4.2)", icon: ClipboardList, route: "/nurse/prescreen", group: "Assessment & LOC" },
      { name: "Care Plan Reviews", icon: Target, route: "/nurse/careplans", group: "Care Plan Governance" },
      { name: "Dedicated Staffing / PCG", icon: HeartHandshake, route: "/nurse/privatecare", group: "Care Plan Governance" },
      { name: "Additional Clinical Services", icon: Cross, route: "/nurse/additionalservices", group: "Care Plan Governance" },
      { name: "Clinical Approvals", icon: BadgeCheck, route: "/nurse/approvalworkflows", group: "Care Plan Governance" },
      { name: "Orders & Prescriptions", icon: FileSignature, route: "/nurse/orders", group: "Shift Endorsement" },
      { name: "Specialist Referrals", icon: Send, route: "/nurse/referrals", group: "Shift Endorsement" },
      { name: "Physician Communication", icon: PhoneCall, route: "/nurse/physiciancomms", group: "Shift Endorsement" },
      { name: "Shift Handover", icon: Repeat, route: "/nurse/shiftendorsements", group: "Shift Endorsement" },
      { name: "Shift Documentation", icon: ClipboardCheck, route: "/nurse/shiftsummary", group: "Shift Endorsement" },
      { name: "Resident Progress Reports", icon: FileText, route: "/nurse/progressreport", group: "Shift Endorsement" },
      { name: "Safeguarding", icon: ShieldCheck, route: "/nurse/safeguarding", group: "Shift Endorsement" },
      { name: "Infection Control", icon: Activity, route: "/nurse/infectioncontrol", group: "Shift Endorsement" },
      { name: "Clinical Reports", icon: BarChart3, route: "/nurse/clinicalreports", group: "Shift Endorsement" },
    ],
  },
  CAREGIVER: {
    name: "On-Duty Caregiver",
    badge: "Daily Assistance",
    desc: "View resident assist checklists, check off task logs, and alert clinical staff of incidents.",
    icon: Users,
    profileName: "Caleb Randall",
    basePath: "/caregiver",
    footerText: "Caregiver Shift Portal",
    sidebarGroupOrder: ["Facility My Shift", "My Residents", "My Care Now", "Document Care", "Need Nurse / Help", "Assignment Update", "Shift Close"],
    sidebarLinks: [
      { name: "Facility My Shift", icon: LayoutDashboard, route: "/caregiver/dashboard", group: "Facility My Shift" },
      { name: "Time In - Clock In / Out", icon: Fingerprint, route: "/caregiver/clockin", group: "Facility My Shift" },
      { name: "My Assigned Residents", icon: UserRound, route: "/caregiver/residents", group: "My Residents" },
      { name: "Assigned Care Plans", icon: Target, route: "/caregiver/careplans", group: "My Residents" },
      { name: "Care Timeline", icon: History, route: "/caregiver/carehistory", group: "My Residents" },
      { name: "My Care Now", icon: ClipboardCheck, route: "/caregiver/todayscare", group: "My Care Now" },
      { name: "Task Cards", icon: ListTodo, route: "/caregiver/taskassignment", group: "My Care Now" },
      { name: "Document Care", icon: NotebookPen, route: "/caregiver/carelogs", group: "Document Care" },
      { name: "Daily Living (ADL)", icon: Accessibility, route: "/caregiver/adlmonitoring", group: "Document Care" },
      { name: "Weight Tracking", icon: Scale, route: "/caregiver/weightmonitoring", group: "Document Care" },
      { name: "Medication Administration (MAR)", icon: Syringe, route: "/caregiver/mar", group: "Document Care" },
      { name: "Need Nurse / Help", icon: Siren, route: "/caregiver/escalations", group: "Need Nurse / Help" },
      { name: "Call Bells", icon: BellRing, route: "/caregiver/callbells", group: "Need Nurse / Help" },
      { name: "Report an Incident", icon: AlertTriangle, route: "/caregiver/incidents", group: "Need Nurse / Help" },
      { name: "Assignment Update", icon: CalendarCheck, route: "/caregiver/caregiverschedule", group: "Assignment Update" },
      { name: "Shift Documentation", icon: ClipboardCheck, route: "/caregiver/shiftsummary", group: "Shift Close" },
      { name: "Shift Handover", icon: Repeat, route: "/caregiver/shiftendorsements", group: "Shift Close" },
      { name: "Endorsement Status", icon: Inbox, route: "/caregiver/endorsementdashboard", group: "Shift Close" },
    ],
  },
  FAMILY: {
    name: "Family Sponsor",
    badge: "Family Portal",
    desc: "Monitor your relative's vitals timeline and check daily comfort summaries.",
    icon: ShieldCheck,
    profileName: "John Pendelton",
    basePath: "/family",
    footerText: "Family Portal",
    sidebarLinks: [
      // Overview
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/family/dashboard", group: "Overview" },
      // Resident Care
      { name: "Monitoring", icon: Activity, route: "/family/relative", group: "Resident Care" },
      { name: "Clinical Records", icon: FolderOpen, route: "/family/clinicalrecords", group: "Resident Care" },
      { name: "One Care · One Journey", icon: Route, route: "/family/residentjourney", group: "Resident Care" },
      { name: "Care Timeline", icon: History, route: "/family/carehistory", group: "Resident Care" },
      { name: "Incident Alerts", icon: AlertTriangle, route: "/family/alerts", group: "Resident Care" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/family/report", group: "Resident Care" },
      { name: "Care Planning", icon: Target, route: "/family/goals", group: "Resident Care" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/family/rounds", group: "Resident Care" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/family/reports", group: "Resident Care" },
      { name: "Sign & Upload", icon: FolderOpen, route: "/family/forms", group: "Resident Care" },
      // Medication
      { name: "Medication Management & Inventory", icon: Pill, route: "/family/medications", group: "Medication" },
      // Coordination & Comms
      { name: "Requests & Approvals", icon: BadgeCheck, route: "/family/approvals", group: "Coordination & Comms" },
      { name: "Sbar Escalation", icon: Siren, route: "/family/escalations", group: "Coordination & Comms" },
      { name: "Appointments", icon: Clock, route: "/family/appointments", group: "Coordination & Comms" },
      // Billing & Finance
      { name: "Billing", icon: Wallet, route: "/family/expenses", group: "Billing & Finance" },
      // Hospitality & Services
      { name: "Hotel Services", icon: ConciergeBell, route: "/family/services", group: "Hospitality & Services" },
      { name: "Community & Events", icon: CalendarDays, route: "/family/community", group: "Hospitality & Services" },
      // Fleet & Transport
      { name: "Transport", icon: Bus, route: "/family/transport", group: "Fleet & Transport" },
    ],
  },
  CARE_MANAGER: {
    name: "Care Manager",
    badge: "Clinical Oversight",
    desc: "Clinical oversight — approvals, incidents, alerts, and care coordination.",
    icon: Stethoscope,
    profileName: "Care Manager",
    basePath: "/care_manager",
    footerText: "Care Manager Portal",
    sidebarGroupOrder: ["Clinical Risk Overview", "Assessment & LOC Governance", "Care Plan Governance", "Care Delivery Reliability", "Safety / Transitions", "Staffing / Team Quality", "Open Decisions"],
    sidebarLinks: [
      { name: "Clinical Governance", icon: LayoutDashboard, route: "/care_manager/dashboard", group: "Clinical Risk Overview" },
      { name: "Clinical Alerts", icon: BellRing, route: "/care_manager/alertcenter", group: "Clinical Risk Overview" },
      { name: "Resident Directory", icon: UserRound, route: "/care_manager/residents", group: "Clinical Risk Overview" },
      { name: "One Care - One Journey", icon: Route, route: "/care_manager/residentjourney", group: "Clinical Risk Overview" },
      { name: "Clinical Records", icon: FolderOpen, route: "/care_manager/clinicalrecords", group: "Clinical Risk Overview" },
      { name: "Care Timeline", icon: History, route: "/care_manager/carehistory", group: "Clinical Risk Overview" },
      { name: "Assessment & LOC Governance", icon: ClipboardList, route: "/care_manager/prescreen", group: "Assessment & LOC Governance" },
      { name: "LOC Decision Review", icon: Gauge, route: "/care_manager/careacuity", group: "Assessment & LOC Governance" },
      { name: "Care Plan Governance", icon: Target, route: "/care_manager/careplans", group: "Care Plan Governance" },
      { name: "Clinical Approvals", icon: BadgeCheck, route: "/care_manager/approvalworkflows", group: "Care Plan Governance" },
      { name: "Today's Approved Care", icon: CalendarCheck, route: "/care_manager/todayscare", group: "Care Delivery Reliability" },
      { name: "Care Delivery Reliability", icon: Activity, route: "/care_manager/caredelivery", group: "Care Delivery Reliability" },
      { name: "Daily Care Logs", icon: NotebookPen, route: "/care_manager/carelogs", group: "Care Delivery Reliability" },
      { name: "Daily Living (ADL)", icon: Accessibility, route: "/care_manager/adlmonitoring", group: "Care Delivery Reliability" },
      { name: "Weight Tracking", icon: Scale, route: "/care_manager/weightmonitoring", group: "Care Delivery Reliability" },
      { name: "Medication Administration (MAR)", icon: Pill, route: "/care_manager/mar", group: "Care Delivery Reliability" },
      { name: "Medication Compliance", icon: PieChart, route: "/care_manager/medcompliance", group: "Care Delivery Reliability" },
      { name: "Safety / Transitions", icon: ShieldCheck, route: "/care_manager/safeguarding", group: "Safety / Transitions" },
      { name: "Incident Reports", icon: AlertTriangle, route: "/care_manager/incidents", group: "Safety / Transitions" },
      { name: "Admissions & Returns", icon: UserPlus, route: "/care_manager/admissions", group: "Safety / Transitions" },
      { name: "Live Safety Monitoring", icon: Video, route: "/care_manager/monitoring", group: "Safety / Transitions" },
      { name: "Wound Care", icon: Bandage, route: "/care_manager/woundcare", group: "Safety / Transitions" },
      { name: "Vital Sign Trends", icon: HeartPulse, route: "/care_manager/vitalstrend", group: "Safety / Transitions" },
      { name: "Infection Control", icon: Activity, route: "/care_manager/infectioncontrol", group: "Safety / Transitions" },
      { name: "Task Assignment", icon: ListTodo, route: "/care_manager/taskassignment", group: "Staffing / Team Quality" },
      { name: "Caregiver Schedule", icon: CalendarCheck, route: "/care_manager/caregiverschedule", group: "Staffing / Team Quality" },
      { name: "Staff Roster", icon: Users, route: "/care_manager/staffroster", group: "Staffing / Team Quality" },
      { name: "Staff Profiles & Records", icon: BadgeCheck, route: "/care_manager/staffprofiles", group: "Staffing / Team Quality" },
      { name: "Quality & Outcomes", icon: TrendingUp, route: "/care_manager/quality", group: "Staffing / Team Quality" },
      { name: "Open Decisions", icon: Siren, route: "/care_manager/escalations", group: "Open Decisions" },
      { name: "Dedicated Staffing / PCG", icon: HeartHandshake, route: "/care_manager/privatecare", group: "Open Decisions" },
      { name: "Additional Clinical Services", icon: Cross, route: "/care_manager/additionalservices", group: "Open Decisions" },
      { name: "Medication Safety", icon: ShieldCheck, route: "/care_manager/medsafety", group: "Open Decisions" },
      { name: "Specialist Referrals", icon: Send, route: "/care_manager/referrals", group: "Open Decisions" },
      { name: "Physician Communication", icon: MessageSquare, route: "/care_manager/physiciancomms", group: "Open Decisions" },
      { name: "Appointments", icon: CalendarDays, route: "/care_manager/appointmentcalendar", group: "Open Decisions" },
      { name: "Follow-up Tracker", icon: CheckCircle, route: "/care_manager/followups", group: "Open Decisions" },
      { name: "Shift Handover", icon: Repeat, route: "/care_manager/shiftendorsements", group: "Open Decisions" },
      { name: "Endorsement Dashboard", icon: Inbox, route: "/care_manager/endorsementdashboard", group: "Open Decisions" },
      { name: "Resident Progress Reports", icon: FileText, route: "/care_manager/progressreport", group: "Open Decisions" },
      { name: "Shift Documentation", icon: ClipboardCheck, route: "/care_manager/shiftsummary", group: "Open Decisions" },
      { name: "Clinical Reports", icon: BarChart3, route: "/care_manager/clinicalreports", group: "Open Decisions" },
      { name: "Clinical Audit Trail", icon: ScrollText, route: "/care_manager/auditlog", group: "Open Decisions" },
    ],
  },
  RESIDENT_COORDINATOR: {
    name: "Resident Coordinator",
    badge: "Resident Coordination",
    desc: "Coordinate appointments, transport, services, events, and move-in readiness without clinical decision authority.",
    icon: HeartHandshake,
    profileName: "Resident Coordinator",
    basePath: "/resident_coordinator",
    footerText: "Resident Coordination Portal",
    sidebarGroupOrder: ["Today", "Residents", "Schedule", "Coordination", "Family Contacts", "Endorsement"],
    sidebarLinks: [
      { name: "Resident Coordination", icon: LayoutDashboard, route: "/resident_coordinator/dashboard", group: "Today" },
      { name: "Resident Snapshot", icon: UserRound, route: "/resident_coordinator/residents", group: "Residents" },
      { name: "Appointments & Activities", icon: CalendarDays, route: "/resident_coordinator/schedule", group: "Schedule" },
      { name: "Open Coordination", icon: Ticket, route: "/resident_coordinator/coordination", group: "Coordination" },
      { name: "Contacts & Update Preferences", icon: Mail, route: "/resident_coordinator/familycontacts", group: "Family Contacts" },
      { name: "Coordination Endorsement", icon: Repeat, route: "/resident_coordinator/endorsement", group: "Endorsement" },
    ],
  },
  FACILITY_ADMIN: {
    name: "Facility Admin",
    badge: "Facility Operations",
    desc: "Manage a single facility's staff, residents, and day-to-day operations.",
    icon: Building2,
    profileName: "Facility Admin",
    basePath: "/facility_admin",
    footerText: "Facility Admin Portal",
    sidebarGroupOrder: ["Today", "Operations", "Residents", "Staff", "Quality", "Services", "Reports", "Settings"],
    sidebarLinks: [
      { name: "Community at a Glance", icon: LayoutDashboard, route: "/facility_admin/dashboard", group: "Today" },
      { name: "Occupancy & Capacity", icon: BedDouble, route: "/facility_admin/occupancy", group: "Operations" },
      { name: "Rooms", icon: DoorOpen, route: "/facility_admin/rooms", group: "Operations" },
      { name: "Purchase Requests", icon: ShoppingCart, route: "/facility_admin/purchaserequests", group: "Operations" },
      { name: "Front Desk", icon: DoorOpen, route: "/facility_admin/frontdesk", group: "Operations" },
      { name: "Unit Turnover", icon: Repeat, route: "/facility_admin/turnover", group: "Operations" },
      { name: "Facility Maintenance", icon: Wrench, route: "/facility_admin/maintenance", group: "Operations" },
      { name: "Resident Directory", icon: UserRound, route: "/facility_admin/residents", group: "Residents" },
      { name: "LOC Mix & Assessment Status", icon: Gauge, route: "/facility_admin/rounds", group: "Residents" },
      { name: "Care Plan Oversight", icon: Target, route: "/facility_admin/careplans", group: "Residents" },
      { name: "Staff Registry", icon: Users, route: "/facility_admin/staff", group: "Staff" },
      { name: "Clinical Alerts", icon: BellRing, route: "/facility_admin/alertcenter", group: "Quality" },
      { name: "Incidents & Safety", icon: AlertTriangle, route: "/facility_admin/incidents", group: "Quality" },
      { name: "Care Delivery & Documentation", icon: ClipboardCheck, route: "/facility_admin/tasks", group: "Quality" },
      { name: "Daily Care Logs", icon: NotebookPen, route: "/facility_admin/carelogs", group: "Quality" },
      { name: "Audit Exceptions", icon: Shield, route: "/facility_admin/auditlog", group: "Quality" },
      { name: "Resident Services", icon: Ticket, route: "/facility_admin/services", group: "Services" },
      { name: "Inventory", icon: Package, route: "/facility_admin/inventory", group: "Services" },
      { name: "Inventory Alerts", icon: Bell, route: "/facility_admin/inventory-alerts", group: "Services" },
      { name: "Concierge", icon: ConciergeBell, route: "/facility_admin/concierge", group: "Services" },
      { name: "Community & Events", icon: CalendarDays, route: "/facility_admin/community", group: "Services" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/facility_admin/reports", group: "Reports" },
      { name: "Clinical & Quality Reports", icon: BarChart3, route: "/facility_admin/clinicalreports", group: "Reports" },
      { name: "Camera Registry", icon: Camera, route: "/facility_admin/cameras", group: "Settings" },
    ],
  },
  BILLING_ADMIN: {
    name: "Billing & Finance",
    badge: "Finance & Billing",
    desc: "Run resident billing end-to-end — service charges, invoice generation, insurance validation, payment processing, and receipts.",
    icon: CircleDollarSign,
    profileName: "Billing & Finance Officer",
    basePath: "/billing_admin",
    footerText: "Billing & Finance Portal",
    sidebarLinks: [
      { name: "Billing Overview", icon: BarChart3, route: "/billing_admin/dashboard" },
      { name: "Resident Billing Records", icon: FolderOpen, route: "/billing_admin/residentbilling" },
      { name: "Transactions Ledger", icon: Wallet, route: "/billing_admin/ledger" },
      { name: "Receivables & Aging", icon: TrendingDown, route: "/billing_admin/receivables" },
      { name: "Revenue by Source", icon: PieChart, route: "/billing_admin/revenue" },
      { name: "Service Charges", icon: ClipboardList, route: "/billing_admin/charges" },
      { name: "Level of Care Pricing", icon: Layers, route: "/billing_admin/loccpricing" },
      { name: "Invoice Generation", icon: FileText, route: "/billing_admin/invoices" },
      { name: "Payment Processing", icon: CreditCard, route: "/billing_admin/payments" },
      { name: "Online Payment", icon: DollarSign, route: "/billing_admin/onlinepayment" },
      { name: "Insurance Validation", icon: ShieldCheck, route: "/billing_admin/insurance" },
      { name: "Receipts", icon: Receipt, route: "/billing_admin/receipts" },
    ],
  },
  PHYSICIAN: {
    name: "Physician",
    badge: "Medical Authority",
    desc: "Oversee the whole care team: diagnose, prescribe & sign, set care directives, answer consults, and review the patient, family, nurse & caregiver record.",
    icon: Stethoscope,
    profileName: "Dr. Alan Reyes",
    basePath: "/physician",
    footerText: "Physician Medical Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/physician/dashboard", group: "Overview" },
      // Resident Care — the up-to-date clinical boards shared with Care Manager.
      { name: "Resident Directory", icon: UserRound, route: "/physician/residents", group: "Resident Care" },
      { name: "Clinical Records", icon: FolderOpen, route: "/physician/clinicalrecords", group: "Resident Care" },
      { name: "Daily Care Logs", icon: NotebookPen, route: "/physician/carelogs", group: "Resident Care" },
      { name: "Care Timeline", icon: History, route: "/physician/carehistory", group: "Resident Care" },
      { name: "Vital Sign Trends", icon: HeartPulse, route: "/physician/vitalstrend", group: "Resident Care" },
      { name: "Weight Tracking", icon: Scale, route: "/physician/weightmonitoring", group: "Resident Care" },
      { name: "Daily Living (ADL)", icon: Accessibility, route: "/physician/adlmonitoring", group: "Resident Care" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/physician/casereview", group: "Resident Care" },
      { name: "Wound Care", icon: Bandage, route: "/physician/woundcare", group: "Resident Care" },
      { name: "Care Plan Reviews", icon: Target, route: "/physician/careplans", group: "Resident Care" },
      // Medication
      { name: "Orders & Prescriptions", icon: Pill, route: "/physician/orders", group: "Medication" },
      { name: "Med Administration (MAR)", icon: Pill, route: "/physician/mar", group: "Medication" },
      { name: "Med Compliance", icon: PieChart, route: "/physician/medcompliance", group: "Medication" },
      { name: "Med Inventory", icon: Package, route: "/physician/medinventory", group: "Medication" },
      { name: "Mini Pharmacy", icon: Cross, route: "/physician/minipharmacy", group: "Medication" },
      // Coordination & Comms
      { name: "Consults", icon: BookOpen, route: "/physician/consults", group: "Coordination & Comms" },
      { name: "Physician Comms Log", icon: Stethoscope, route: "/physician/physiciancomms", group: "Coordination & Comms" },
      { name: "Referrals & Appointments", icon: CalendarCheck, route: "/physician/referrals", group: "Coordination & Comms" },
      { name: "SBAR Escalation", icon: Siren, route: "/physician/escalations", group: "Coordination & Comms" },
      { name: "Clinical Notes", icon: PenTool, route: "/physician/notes", group: "Coordination & Comms" },
      { name: "Progress Reports", icon: FileText, route: "/physician/progressreport", group: "Coordination & Comms" },
      // Operations
      { name: "Incident Medical Review", icon: AlertTriangle, route: "/physician/incidents", group: "Operations" },
      // Administration
      { name: "Audit Log", icon: Shield, route: "/physician/auditlog", group: "Administration" },
    ],
  },
  RESIDENT: {
    name: "Resident / Patient",
    badge: "My Care",
    desc: "View your own health timeline, daily reports, messages, and appointments.",
    icon: UserRound,
    profileName: "Arthur Pendelton",
    basePath: "/resident",
    footerText: "Resident My Care Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/resident/dashboard" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/resident/report" },
      { name: "Messages", icon: MessageSquare, route: "/resident/messages" },
      { name: "Appointments", icon: Clock, route: "/resident/appointments" },
      { name: "Transport", icon: Bus, route: "/resident/transport" },
      { name: "Hotel Services", icon: ConciergeBell, route: "/resident/services" },
      { name: "Community & Events", icon: CalendarDays, route: "/resident/community" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/resident/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/resident/rounds" },
      { name: "Care Planning", icon: Target, route: "/resident/careplans" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/resident/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/resident/medications" },
      { name: "Sbar Escalation", icon: Siren, route: "/resident/escalations" },
      { name: "Vaccinations", icon: Syringe, route: "/resident/vaccinations" },
      { name: "Resident Documents", icon: FolderOpen, route: "/resident/documents" },
      { name: "Clinical Reports", icon: BarChart3, route: "/resident/clinicalreports" },
    ],
  },
  FLEET_MANAGEMENT: {
    name: "Fleet Manager",
    badge: "Fleet & Transport",
    desc: "Dispatch resident transport, track live trips, and keep the vehicle fleet compliant and road-ready.",
    icon: Bus,
    profileName: "Marcus Dela Cruz",
    basePath: "/fleet_management",
    footerText: "Fleet & Transport Portal",
    sidebarLinks: [
      { name: "Fleet Dashboard", icon: Grid, route: "/fleet_management/dashboard" },
      { name: "Transport Requests", icon: ClipboardList, route: "/fleet_management/requests" },
      { name: "Ambulance Booking", icon: Ambulance, route: "/fleet_management/ambulance" },
      { name: "Trip Board", icon: Route, route: "/fleet_management/trips" },
      { name: "Vehicles", icon: Car, route: "/fleet_management/vehicles" },
      { name: "Drivers", icon: Users, route: "/fleet_management/drivers" },
      { name: "Fleet Maintenance", icon: Wrench, route: "/fleet_management/maintenance" },
      { name: "Fuel & Odometer", icon: Fuel, route: "/fleet_management/fuel" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/fleet_management/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/fleet_management/rounds" },
      { name: "Care Planning", icon: Target, route: "/fleet_management/careplans" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/fleet_management/tasks" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/fleet_management/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/fleet_management/medications" },
      { name: "Sbar Escalation", icon: Siren, route: "/fleet_management/escalations" },
    ],
  },
  DRIVER: {
    name: "Transport Driver",
    badge: "Logistics",
    desc: "Perform vehicle safety inspections, log odometer and fuel, and manage active transport requests.",
    icon: Car,
    profileName: "Eduardo Lopez",
    basePath: "/driver",
    footerText: "Driver Dispatch Portal",
    sidebarLinks: [
      { name: "Shift Dashboard", icon: Grid, route: "/driver/dashboard" },
      { name: "Trip Board", icon: Route, route: "/driver/trips" },
      { name: "Inspection Checklist", icon: ClipboardList, route: "/driver/checklist" },
      { name: "Fuel & Odometer", icon: Fuel, route: "/driver/fuel" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/driver/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/driver/rounds" },
      { name: "Care Planning", icon: Target, route: "/driver/careplans" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/driver/tasks" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/driver/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/driver/medications" },
      { name: "Sbar Escalation", icon: Siren, route: "/driver/escalations" },
    ],
  },
  SECURITY: {
    name: "Security Guard",
    badge: "Safety & Security",
    desc: "Log patrols and shift activity, file incident reports (e.g. a resident near the gate), and watch camera alerts.",
    icon: Shield,
    profileName: "Security Officer",
    basePath: "/security",
    footerText: "Security Command Portal",
    sidebarLinks: [
      { name: "Security Command", icon: Grid, route: "/security/dashboard" },
      { name: "Security & Incident Log", icon: AlertTriangle, route: "/security/securitylog" },
      { name: "Camera Activity Log", icon: Activity, route: "/security/cameralogs" },
      { name: "Time Clock", icon: Timer, route: "/security/timeclock" },
    ],
  },
  NUTRITIONIST: {
    name: "Nutritionist",
    badge: "Dietary & Nutrition",
    desc: "Set each resident's diet orders (diet type, restrictions, target meals), manage the daily menu, and review the kitchen cook list.",
    icon: Utensils,
    profileName: "Facility Nutritionist",
    basePath: "/nutritionist",
    footerText: "Nutrition & Dietary Portal",
    sidebarLinks: [
      { name: "Diet & Nutrition Orders", icon: Utensils, route: "/nutritionist/dietorders" },
      { name: "Kitchen — Cook List", icon: Grid, route: "/nutritionist/kitchen" },
      { name: "Dining & Compliance", icon: Utensils, route: "/nutritionist/dining" },
    ],
  },
  KITCHEN: {
    name: "Kitchen Staff",
    badge: "Food Service",
    desc: "See today's cook list — the active diet orders per resident, grouped by meal, so you know exactly what to prepare.",
    icon: Utensils,
    profileName: "Kitchen Staff",
    basePath: "/kitchen",
    footerText: "Kitchen Cook List Portal",
    sidebarLinks: [
      { name: "Kitchen — Cook List", icon: Utensils, route: "/kitchen/kitchen" },
    ],
  },
  HOUSEKEEPING: {
    name: "Housekeeping",
    badge: "Rooms & Cleaning",
    desc: "Work the housekeeping & laundry queue from residents, and keep room-turnover status current (make-ready → occupied).",
    icon: Sparkles,
    profileName: "Housekeeping Staff",
    basePath: "/housekeeping",
    footerText: "Housekeeping Portal",
    sidebarLinks: [
      { name: "Housekeeping Requests", icon: Sparkles, route: "/housekeeping/dashboard" },
      { name: "Unit Turnover", icon: BedDouble, route: "/housekeeping/turnover" },
    ],
  },
  MAINTENANCE: {
    name: "Maintenance",
    badge: "Repairs & Engineering",
    desc: "Work resident repair & HVAC tickets, and manage preventative facility-system maintenance schedules.",
    icon: Wrench,
    profileName: "Maintenance Staff",
    basePath: "/maintenance",
    footerText: "Maintenance Portal",
    sidebarLinks: [
      { name: "Maintenance Requests", icon: Wrench, route: "/maintenance/dashboard" },
      { name: "Facility Maintenance", icon: Wrench, route: "/maintenance/maintenance" },
    ],
  },
};

// ─────────────────────────────────────────────────────────────
// Sidebar grouping — mirrors the SLMS Feature Matrix modules so the
// nav renders as collapsible "group selections" instead of one long
// flat list. SIDEBAR_GROUP_ORDER defines the order groups appear in.
// ─────────────────────────────────────────────────────────────
export const SIDEBAR_GROUP_ORDER = [
  // Care360 role-based primary navigation (brief v1.1, page 10).
  "Shift Command",
  "Clinical Triage Queue",
  "Caregiver Deployment",
  "Shift Watchlist",
  "Care Delivery Status",
  "Assessment & LOC",
  "Care Plan Governance",
  "Shift Endorsement",
  "Facility My Shift",
  "My Care Now",
  "Document Care",
  "Need Nurse / Help",
  "Assignment Update",
  "Clinical Risk Overview",
  "Assessment & LOC Governance",
  "Care Delivery Reliability",
  "Safety / Transitions",
  "Staffing / Team Quality",
  "Open Decisions",
  "Today",
  "Clinical Overview",
  "My Shift",
  "Operations",
  "Residents",
  "My Residents",
  "Staff",
  "Assess & LOC",
  "Care Plans",
  "Care Tasks",
  "Reviews",
  "Team",
  "Clinical Review",
  "Quality",
  "Schedule",
  "Coordination",
  "Family Contacts",
  "Endorsement",
  "Request Help",
  "Shift Close",
  "Services",
  "Reports",
  "Settings",
  // Legacy module groups retained for roles outside this brief.
  "Overview",
  "Clinical Monitoring",
  "Resident Care",
  "Resident Records",
  "Medication",
  "Coordination & Comms",
  "Operations",
  "Inventory",
  "Billing & Finance",
  "Hospitality & Services",
  "Fleet & Transport",
  "KPI Reports",
  "Administration",
] as const;

export type SidebarGroup = (typeof SIDEBAR_GROUP_ORDER)[number];

const LINK_GROUP_MAP: Record<string, SidebarGroup> = {
  // Overview
  "Reporting & Care Intelligence": "Overview",
  "Fleet Dashboard": "Overview",
  "Shift Dashboard": "Overview",
  "Overview": "Overview",
  "Customer Workspaces": "Operations",
  "Plans & Entitlements": "Administration",
  "Usage & Capacity": "Operations",
  "Access": "Administration",
  "Security & Audit": "Administration",
  "System Health": "Administration",
  "Platform Settings": "Administration",
  "Organization Overview": "Overview",
  "Communities": "Operations",
  "People & Access": "Operations",
  "Pending Approvals": "Administration",
  "Register Staff": "Administration",
  "Usage & Subscription": "Administration",
  "Invoices": "Administration",
  "Organization Branding": "Administration",
  "Organization Audit": "Administration",
  // Resident Care (Modules 1–4)
  "Resident Profile & Care Record": "Resident Care",
  "Daily Care Logs": "Resident Care",
  "Care Logs": "Resident Care",
  "Care History": "Resident Care",
  "One Care · One Journey": "Resident Care",
  "Clinical Records": "Resident Care",
  "Staff Profiles & Records": "Administration",
  "Time In · Clock In / Out": "Overview",
  "Geofencing": "Administration",
  "Vitals Trend": "Resident Care",
  "ADL Monitoring": "Resident Care",
  "Weight Monitoring": "Resident Care",
  "Shift Summary": "Resident Care",
  "Care Acuity & Level of Care": "Resident Care",
  "Wound Care": "Resident Care",
  "Resident Progress Report": "Resident Care",
  "Appointment Calendar": "Coordination & Comms",
  "Shift Endorsements": "Coordination & Comms",
  "Pre-Admission Assessment": "Resident Care",
  "Assessment & Level of Care": "Resident Care",
  "Labs & Allergies": "Resident Care",
  "Care Planning": "Resident Care",
  "Daily Care Documentation & Monitoring": "Resident Care",
  "Task Assignment": "Resident Care",
  "Vaccinations": "Resident Care",
  "Resident Documents": "Resident Care",
  "Camera Activity Log": "Resident Care",
  // Guard / Security
  "Security Command": "Overview",
  "Security & Incident Log": "Operations",
  // Kitchen / Diet & Nutrition
  "Diet & Nutrition Orders": "Hospitality & Services",
  "Kitchen — Cook List": "Hospitality & Services",
  "Housekeeping Requests": "Hospitality & Services",
  "Maintenance Requests": "Hospitality & Services",
  // Medication (Module 6)
  "Medication Management & Inventory": "Medication",
  "Medication Administration Record": "Medication",
  "Medication Compliance": "Medication",
  "Medication Inventory": "Medication",
  "Orders & Prescriptions": "Medication",
  "Approvals": "Medication",
  "Inventory Alerts": "Medication",
  "Physician Comms Log": "Coordination & Comms",
  "Referrals & Appointments": "Coordination & Comms",
  // Coordination & Comms (Modules 5, 7)
  "Sbar Escalation": "Coordination & Comms",
  "Care Team": "Coordination & Comms",
  "Call Bells": "Coordination & Comms",
  "Shift Endorsement & Continuity": "Coordination & Comms",
  "Consults & Referrals": "Coordination & Comms",
  "Follow-up Tracker": "Coordination & Comms",
  "Clinical Notes": "Coordination & Comms",
  "Secure Messages": "Coordination & Comms",
  "Messages": "Coordination & Comms",
  "Alerts": "Coordination & Comms",
  "Alert Center": "Clinical Monitoring",
  "Appointments": "Coordination & Comms",
  // Operations (facility, staff, incidents, billing, reports)
  "Staff Registry": "Operations",
  "Staff": "Operations",
  "Time Clock": "Operations",
  "CRM & Leads": "Operations",
  "Admissions & Registration": "Operations",
  "Rooms": "Operations",
  "Occupancy": "Operations",
  "Incidents": "Operations",
  "Incident Review": "Operations",
  "Incident Medical Review": "Operations",
  "Billing": "Operations",
  "Purchase Requests": "Operations",
  "Clinical Reports": "Operations",
  // Billing & Finance (dedicated BILLING_ADMIN portal)
  "Billing Overview": "Billing & Finance",
  "Transactions Ledger": "Billing & Finance",
  "Receivables & Aging": "Billing & Finance",
  "Revenue by Source": "Billing & Finance",
  "Service Charges": "Billing & Finance",
  "Invoice Generation": "Billing & Finance",
  "Payment Processing": "Billing & Finance",
  "Online Payment": "Billing & Finance",
  "Insurance Validation": "Billing & Finance",
  "Receipts": "Billing & Finance",
  // Hospitality & Services (Module 14 — PMS)
  "Dining & Compliance": "Hospitality & Services",
  "Resident Services": "Hospitality & Services",
  "Hotel Services": "Hospitality & Services",
  "Concierge": "Hospitality & Services",
  "Front Desk": "Hospitality & Services",
  "Unit Turnover": "Hospitality & Services",
  "Community & Events": "Hospitality & Services",
  "Facility Maintenance": "Hospitality & Services",
  "Transport": "Hospitality & Services",
  // Fleet & Transport (Module 13)
  "Transport Requests": "Fleet & Transport",
  "Ambulance Booking": "Fleet & Transport",
  "Trip Board": "Fleet & Transport",
  "Vehicles": "Fleet & Transport",
  "Drivers": "Fleet & Transport",
  "Fleet Maintenance": "Fleet & Transport",
  "Fuel & Odometer": "Fleet & Transport",
  "Inspection Checklist": "Fleet & Transport",
  // Administration (governance, system tools)
  "SLMS Feature Matrix": "Administration",
  "AI Assistant": "Administration",
  "Landing Studio": "Administration",
  "Portal Matrix": "Administration",
  "Audit Log": "Administration",
};

export const getSidebarGroup = (linkName: string): SidebarGroup =>
  LINK_GROUP_MAP[linkName] || "Overview";

/**
 * Group an ordered list of sidebar links into matrix-based sections,
 * preserving each link's original order within its group and dropping
 * any group that has no links for the current role/matrix.
 */
export const groupSidebarLinks = (
  links: SidebarLink[],
  preferredOrder: readonly SidebarGroup[] = SIDEBAR_GROUP_ORDER,
): { group: SidebarGroup; links: SidebarLink[] }[] => {
  const buckets = new Map<SidebarGroup, SidebarLink[]>();
  for (const link of links) {
    const g = link.group ?? getSidebarGroup(link.name);
    const bucket = buckets.get(g);
    if (bucket) bucket.push(link);
    else buckets.set(g, [link]);
  }
  const orderedGroups = [
    ...preferredOrder,
    ...SIDEBAR_GROUP_ORDER.filter((group) => !preferredOrder.includes(group)),
  ];
  return orderedGroups.filter((g) => buckets.has(g)).map((g) => ({
    group: g,
    links: buckets.get(g)!,
  }));
};

export const getRoleDetails = (role: Role): RoleDetails => {
  return ROLES[role] || ROLES.FAMILY;
};

export const getRoleFromPath = (pathSegment: string): Role => {
  return PATH_TO_ROLE[pathSegment] || "FAMILY";
};

export const getTabName = (tabSegment: string): string => {
  return ROUTE_TO_TAB[tabSegment] || "Dashboard";
};

export interface FeatureInfo {
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  routeSegment: string;
}

export const GLOBAL_FEATURES: Record<string, FeatureInfo> = {
  "Reporting & Care Intelligence": { name: "Reporting & Care Intelligence", icon: Grid, routeSegment: "dashboard" },
  "Resident Profile & Care Record": { name: "Resident Profile & Care Record", icon: ShieldCheck, routeSegment: "records" },
  "Assessment & Level of Care": { name: "Assessment & Level of Care", icon: ClipboardList, routeSegment: "rounds" },
  "Medication Management & Inventory": { name: "Medication Management & Inventory", icon: Pill, routeSegment: "medications" },
  "Care Planning": { name: "Care Planning", icon: Target, routeSegment: "careplans" },
  "Sbar Escalation": { name: "Sbar Escalation", icon: Siren, routeSegment: "escalations" },
  "Shift Endorsement & Continuity": { name: "Shift Endorsement & Continuity", icon: FileText, routeSegment: "reports" },
  "Daily Care Documentation & Monitoring": { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, routeSegment: "tasks" },
  "Admissions & Registration": { name: "Admissions & Registration", icon: UserPlus, routeSegment: "admissions" },
  "Staff Registry": { name: "Staff Registry", icon: Users, routeSegment: "staff" },
  "Staff": { name: "Staff", icon: Users, routeSegment: "staff" },
  "AI Assistant": { name: "AI Assistant", icon: Sparkles, routeSegment: "assistant" },
  "Landing Studio": { name: "Landing Studio", icon: Palette, routeSegment: "appearance" },
  "Portal Matrix": { name: "Portal Matrix", icon: ShieldCheck, routeSegment: "matrix" },
  "Incident Log": { name: "Incident Log", icon: AlertTriangle, routeSegment: "incidents" },
  "Incidents": { name: "Incidents", icon: AlertTriangle, routeSegment: "incidents" },
  "Time Clock": { name: "Time Clock", icon: Timer, routeSegment: "timeclock" },
  "Alerts": { name: "Alerts", icon: AlertTriangle, routeSegment: "alerts" },
  "Messages": { name: "Messages", icon: MessageSquare, routeSegment: "messages" },
  "Appointments": { name: "Appointments", icon: Clock, routeSegment: "appointments" },
  "Billing": { name: "Billing", icon: DollarSign, routeSegment: "billing" },
  "Expenses": { name: "Expenses", icon: DollarSign, routeSegment: "expenses" },
  "Rooms": { name: "Rooms", icon: DoorOpen, routeSegment: "rooms" },
  "Occupancy": { name: "Occupancy", icon: BedDouble, routeSegment: "occupancy" },
  "Call Bells": { name: "Call Bells", icon: BellRing, routeSegment: "callbells" },
  "Care Team": { name: "Care Team", icon: Stethoscope, routeSegment: "careteam" },
  "Transport Requests": { name: "Transport Requests", icon: ClipboardList, routeSegment: "requests" },
  "Trip Board": { name: "Trip Board", icon: Route, routeSegment: "trips" },
  "Vehicles": { name: "Vehicles", icon: Car, routeSegment: "vehicles" },
  "Drivers": { name: "Drivers", icon: Users, routeSegment: "drivers" },
  "Fleet Maintenance": { name: "Fleet Maintenance", icon: Wrench, routeSegment: "maintenance" },
  "Fuel & Odometer": { name: "Fuel & Odometer", icon: Fuel, routeSegment: "fuel" },
  "Transport": { name: "Transport", icon: Bus, routeSegment: "transport" },
  "Dining & Compliance": { name: "Dining & Compliance", icon: Utensils, routeSegment: "dining" },
  "Resident Services": { name: "Resident Services", icon: Ticket, routeSegment: "services" },
  "Concierge": { name: "Concierge", icon: ConciergeBell, routeSegment: "concierge" },
  "Hotel Services": { name: "Hotel Services", icon: ConciergeBell, routeSegment: "services" },
  "Front Desk": { name: "Front Desk", icon: DoorOpen, routeSegment: "frontdesk" },
  "Unit Turnover": { name: "Unit Turnover", icon: Repeat, routeSegment: "turnover" },
  "Community & Events": { name: "Community & Events", icon: CalendarDays, routeSegment: "community" },
  "Orders & Prescriptions": { name: "Orders & Prescriptions", icon: Pill, routeSegment: "orders" },
  "Clinical Notes": { name: "Clinical Notes", icon: PenTool, routeSegment: "notes" },
  "Incident Review": { name: "Incident Review", icon: AlertTriangle, routeSegment: "incidents" },
  "Secure Messages": { name: "Secure Messages", icon: MessageSquare, routeSegment: "messages" },
  "Case Review": { name: "Case Review", icon: ClipboardList, routeSegment: "casereview" },
  "Consults & Referrals": { name: "Consults & Referrals", icon: BookOpen, routeSegment: "consults" },
  "Incident Medical Review": { name: "Incident Medical Review", icon: AlertTriangle, routeSegment: "incidents" },
  "Vaccinations": { name: "Vaccinations", icon: Syringe, routeSegment: "vaccinations" },
  "Resident Documents": { name: "Resident Documents", icon: FolderOpen, routeSegment: "documents" },
  "Medication Administration Record": { name: "Medication Administration Record", icon: Pill, routeSegment: "mar" },
  "Follow-up Tracker": { name: "Follow-up Tracker", icon: CalendarCheck, routeSegment: "followups" },
  "Audit Log": { name: "Audit Log", icon: Shield, routeSegment: "auditlog" },
  "Inventory Alerts": { name: "Inventory Alerts", icon: Bell, routeSegment: "inventory-alerts" },
  "Clinical Reports": { name: "Clinical Reports", icon: BarChart3, routeSegment: "clinicalreports" },
  "Daily Care Logs": { name: "Daily Care Logs", icon: NotebookPen, routeSegment: "carelogs" },
  "SLMS Feature Matrix": { name: "SLMS Feature Matrix", icon: ShieldCheck, routeSegment: "featurematrix" },
};
