import {
  Grid,
  Activity,
  Users,
  Settings,
  ShieldCheck,
  AlertTriangle,
  CheckCircle,
  Clock,
  User,
  MessageSquare,
  DollarSign,
  Palette,
  Sparkles,
  Building2,
  Stethoscope,
  UserRound,
  UserPlus,
  DoorOpen,
  BedDouble,
  Package,
  FileText,
  Pill,
  BellRing,
  Timer,
  ClipboardList,
  BookOpen,
  PenTool,
  Target,
  Bus,
  Ambulance,
  Car,
  Route,
  Wrench,
  Fuel,
  Utensils,
  Ticket,
  ConciergeBell,
  Repeat,
  CalendarDays,
  Siren,
  Syringe,
  FolderOpen,
  CalendarCheck,
  BarChart3,
  Shield,
  ClipboardCheck,
  Bell,
  LayoutDashboard,
  Gauge,
  Mail,
  ServerCog,
  CircleDollarSign,
  CreditCard,
  Receipt,
  Wallet,
  PieChart,
  TrendingDown,
  ShoppingCart,
  Camera,
} from "lucide-react";

export type Role =
  | "PLATFORM_ADMIN"
  | "ORGANIZATION_ADMIN"
  | "SUPERADMIN"
  | "FACILITY_ADMIN"
  | "CARE_MANAGER"
  | "BILLING_ADMIN"
  | "PHYSICIAN"
  | "NURSE"
  | "CAREGIVER"
  | "FAMILY"
  | "RESIDENT"
  | "FLEET_MANAGEMENT"
  | "DRIVER"
  | "SECURITY"
  | "NUTRITIONIST"
  | "KITCHEN"
  | "HOUSEKEEPING"
  | "MAINTENANCE";

export interface SidebarLink {
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  route: string;
  /** Optional per-link sidebar group override (wins over the name-based map). */
  group?: SidebarGroup;
}

export interface RoleDetails {
  name: string;
  badge: string;
  desc: string;
  icon: React.ComponentType<{ className?: string }>;
  profileName: string;
  footerText: string;
  basePath: string;
  sidebarLinks: SidebarLink[];
}

export const ROUTE_TO_TAB: Record<string, string> = {
  dashboard: "Reporting & Care Intelligence",
  monitoring: "Vitals Monitor",
  incidents: "Incident Log",
  records: "Resident Profile & Care Record",
  staff: "Staff Registry",
  tasks: "Daily Care Documentation & Monitoring",
  residents: "Resident Profile & Care Record",
  reports: "Shift Endorsement & Continuity",
  relative: "Resident Profile & Care Record",
  timeline: "Health Timeline",
  report: "Daily Care Documentation & Monitoring",
  alerts: "Alerts",
  alertcenter: "Alert Center",
  messages: "Messages",
  photos: "Photos",
  appointments: "Appointments",
  expenses: "Billing",
  goals: "Care Planning",
  admin: "Reporting & Care Intelligence",
  shift: "Reporting & Care Intelligence",
  family: "Reporting & Care Intelligence",
  appearance: "Landing Studio",
  assistant: "AI Assistant",
  matrix: "Portal Matrix",
  crm: "CRM & Leads",
  leads: "CRM & Leads",
  consentforms: "Consent & Move-in Forms",
  forms: "Sign & Upload",
  admissions: "Admissions & Registration",
  registration: "Admissions & Registration",
  rooms: "Rooms",
  occupancy: "Occupancy",
  billing: "Billing",
  ledger: "Transactions Ledger",
  receivables: "Receivables & Aging",
  revenue: "Revenue by Source",
  charges: "Service Charges",
  invoices: "Invoice Generation",
  payments: "Payment Processing",
  insurance: "Insurance Validation",
  receipts: "Receipts",
  onlinepayment: "Online Payment",
  inventory: "Inventory",
  purchaserequests: "Purchase Requests",
  medications: "Medication Management & Inventory",
  callbells: "Call Bells",
  timeclock: "Time Clock",
  rounds: "Assessment & Level of Care",
  casereview: "Assessment & Level of Care",
  careplans: "Care Planning",
  consults: "Consults & Referrals",
  escalations: "Clinical Coordination",
  orders: "Medication Management & Inventory",
  approvalworkflows: "Medication Approvals",
  physiciancomms: "Physician Comms Log",
  referrals: "Referrals & Appointments",
  notes: "Clinical Notes",
  vitals: "Vitals Trends",
  careteam: "Care Team",
  requests: "Transport Requests",
  ambulance: "Ambulance Booking",
  trips: "Trip Board",
  vehicles: "Vehicles",
  drivers: "Drivers",
  maintenance: "Maintenance",
  fuel: "Fuel & Odometer",
  transport: "Transport",
  dining: "Dining & Compliance",
  checklist: "Inspection Checklist",
  services: "Resident Services",
  concierge: "Concierge",
  frontdesk: "Front Desk",
  turnover: "Unit Turnover",
  community: "Community & Events",
  documentation: "Daily Care Documentation & Monitoring",
  vaccinations: "Vaccinations",
  documents: "Resident Documents",
  mar: "Medication Administration Record",
  followups: "Follow-up Tracker",
  auditlog: "Audit Log",
  "inventory-alerts": "Inventory Alerts",
  clinicalreports: "Clinical Reports",
  taskboard: "Task Assignment",
  securitylog: "Security & Incident Log",
  cameralogs: "Camera Activity Log",
  dietorders: "Diet & Nutrition Orders",
  kitchen: "Kitchen — Cook List",
  dailyrounds: "Daily Rounds — Bedside Documentation",
  featurematrix: "SLMS Feature Matrix & System Overview",
  workspaces: "Customer Workspaces",
  plans: "Plans & Entitlements",
  usage: "Usage & Capacity",
  access: "Invitations & Access",
  security: "Security & Audit",
  health: "System Health",
  platformsettings: "Platform Settings",
  communities: "Communities",
  people: "People & Access",
  approvals: "Pending Approvals",
  invitations: "Staff Invitations",
  subscription: "Usage & Subscription",
  branding: "Organization Branding",
  audit: "Organization Audit",
};

export const PATH_TO_ROLE: Record<string, Role> = {
  platform_admin: "PLATFORM_ADMIN",
  organization_admin: "ORGANIZATION_ADMIN",
  nurse: "NURSE",
  superadmin: "SUPERADMIN",
  caregiver: "CAREGIVER",
  family: "FAMILY",
  facility_admin: "FACILITY_ADMIN",
  care_manager: "CARE_MANAGER",
  billing_admin: "BILLING_ADMIN",
  physician: "PHYSICIAN",
  resident: "RESIDENT",
  fleet_management: "FLEET_MANAGEMENT",
  driver: "DRIVER",
  security: "SECURITY",
  nutritionist: "NUTRITIONIST",
  kitchen: "KITCHEN",
  housekeeping: "HOUSEKEEPING",
  maintenance: "MAINTENANCE",
};

export const ROLES: Record<Role, RoleDetails> = {
  PLATFORM_ADMIN: {
    name: "Platform Admin",
    badge: "Platform Admin",
    desc: "Provision and govern SaaS customer organizations, communities, plans, and subscriptions.",
    icon: ShieldCheck,
    profileName: "Platform Administrator",
    basePath: "/platform_admin",
    footerText: "Platform Admin Portal",
    sidebarLinks: [
      { name: "Overview", icon: LayoutDashboard, route: "/platform_admin/dashboard" },
      { name: "Customer Workspaces", icon: Building2, route: "/platform_admin/workspaces" },
      { name: "Plans & Entitlements", icon: CircleDollarSign, route: "/platform_admin/plans" },
      { name: "Usage & Capacity", icon: Gauge, route: "/platform_admin/usage" },
      { name: "Invitations & Access", icon: Mail, route: "/platform_admin/access" },
      { name: "Security & Audit", icon: Shield, route: "/platform_admin/security" },
      { name: "System Health", icon: Activity, route: "/platform_admin/health" },
      { name: "Platform Settings", icon: ServerCog, route: "/platform_admin/platformsettings" },
    ],
  },
  ORGANIZATION_ADMIN: {
    name: "Organization Admin",
    badge: "Organization Admin",
    desc: "Manage company communities, people, invitations, access, subscription usage, and tenant configuration.",
    icon: Building2,
    profileName: "Organization Administrator",
    basePath: "/organization_admin",
    footerText: "Organization Admin Portal",
    sidebarLinks: [
      { name: "Organization Overview", icon: LayoutDashboard, route: "/organization_admin/dashboard" },
      { name: "Communities", icon: Building2, route: "/organization_admin/communities" },
      { name: "People & Access", icon: Users, route: "/organization_admin/people" },
      { name: "Pending Approvals", icon: ClipboardCheck, route: "/organization_admin/approvals" },
      { name: "Staff Invitations", icon: Mail, route: "/organization_admin/invitations" },
      { name: "Usage & Subscription", icon: Gauge, route: "/organization_admin/subscription" },
      { name: "Organization Branding", icon: Palette, route: "/organization_admin/branding" },
      { name: "Organization Audit", icon: Shield, route: "/organization_admin/audit" },
    ],
  },
  SUPERADMIN: {
    name: "Administrator",
    badge: "Full System Access",
    desc: "Full system access — approvals, audit, staff registries, and system-wide oversight.",
    icon: Settings,
    profileName: "Administrator",
    basePath: "/superadmin",
    footerText: "Super Admin Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/superadmin/dashboard" },
      { name: "SLMS Feature Matrix", icon: ShieldCheck, route: "/superadmin/featurematrix" },
      { name: "Alert Center", icon: BellRing, route: "/superadmin/alertcenter", group: "Clinical Monitoring" },
      { name: "Daily Rounds (10-Area Bedside)", icon: ClipboardCheck, route: "/superadmin/dailyrounds" },
      { name: "Camera Activity Log", icon: Activity, route: "/superadmin/cameralogs" },
      // "Portal Matrix" is merged into "SLMS Feature Matrix" as its Access Control tab.
      { name: "CRM & Leads", icon: UserPlus, route: "/superadmin/crm" },
      { name: "Consent & Move-in Forms", icon: ClipboardList, route: "/superadmin/consentforms" },
      { name: "Admissions & Registration", icon: UserPlus, route: "/superadmin/admissions" },
      { name: "Staff Registry", icon: Users, route: "/superadmin/staff" },
      { name: "AI Assistant", icon: Sparkles, route: "/superadmin/assistant" },
      { name: "Landing Studio", icon: Palette, route: "/superadmin/appearance" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/superadmin/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/superadmin/rounds" },
      { name: "Care Planning", icon: Target, route: "/superadmin/careplans" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/superadmin/tasks" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/superadmin/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/superadmin/medications" },
      { name: "Clinical Coordination", icon: Siren, route: "/superadmin/escalations" },
      { name: "Vaccinations", icon: Syringe, route: "/superadmin/vaccinations" },
      { name: "Resident Documents", icon: FolderOpen, route: "/superadmin/documents" },
      { name: "Medication Administration Record", icon: Pill, route: "/superadmin/mar" },
      { name: "Medication Approvals", icon: ClipboardCheck, route: "/superadmin/approvalworkflows", group: "Medication" },
      { name: "Audit Log", icon: Shield, route: "/superadmin/auditlog" },
      { name: "Inventory Alerts", icon: Bell, route: "/superadmin/inventory-alerts" },
      { name: "Clinical Reports", icon: BarChart3, route: "/superadmin/clinicalreports" },
    ],
  },
  NURSE: {
    name: "Head Nurse",
    badge: "Clinical Care",
    desc: "Access real-time resident vitals, receive instant fall detection warnings, and log via Voice AI.",
    icon: Activity,
    profileName: "Sarah Jenkins, RN",
    basePath: "/nurse",
    footerText: "Nurse Clinical Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/nurse/dashboard" },
      { name: "Alert Center", icon: BellRing, route: "/nurse/alertcenter", group: "Clinical Monitoring" },
      { name: "Task Assignment", icon: ClipboardList, route: "/nurse/taskboard", group: "Clinical Monitoring" },
      { name: "Camera Activity Log", icon: Camera, route: "/nurse/cameralogs", group: "Clinical Monitoring" },
      { name: "Daily Rounds (10-Area Bedside)", icon: ClipboardCheck, route: "/nurse/dailyrounds", group: "Clinical Monitoring" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/nurse/rounds" },
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/nurse/records" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/nurse/medications" },
      { name: "Care Planning", icon: Target, route: "/nurse/careplans" },
      { name: "Clinical Notes", icon: FileText, route: "/nurse/notes" },
      { name: "Clinical Coordination", icon: Siren, route: "/nurse/escalations" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/nurse/reports" },
      { name: "Orders & Prescriptions", icon: Pill, route: "/nurse/orders" },
      { name: "Medication Approvals", icon: ClipboardCheck, route: "/nurse/approvalworkflows" },
      { name: "Physician Comms Log", icon: Stethoscope, route: "/nurse/physiciancomms" },
      { name: "Referrals & Appointments", icon: CalendarCheck, route: "/nurse/referrals" },
      { name: "Incident Reports", icon: AlertTriangle, route: "/nurse/incidents", group: "Clinical Monitoring" },
      { name: "Secure Messages", icon: MessageSquare, route: "/nurse/messages" },
      // Core SLMS Modules Aligned
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/nurse/tasks" },
      { name: "Vaccinations", icon: Syringe, route: "/nurse/vaccinations" },
      { name: "Resident Documents", icon: FolderOpen, route: "/nurse/documents" },
      { name: "Medication Administration Record", icon: Pill, route: "/nurse/mar", group: "Clinical Monitoring" },
      { name: "Follow-up Tracker", icon: CalendarCheck, route: "/nurse/followups" },
      { name: "Audit Log", icon: Shield, route: "/nurse/auditlog" },
      { name: "Clinical Reports", icon: BarChart3, route: "/nurse/clinicalreports" },
    ],
  },
  CAREGIVER: {
    name: "On-Duty Caregiver",
    badge: "Daily Assistance",
    desc: "View resident assist checklists, check off task logs, and alert clinical staff of incidents.",
    icon: Users,
    profileName: "Caleb Randall",
    basePath: "/caregiver",
    footerText: "Caregiver Shift Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/caregiver/dashboard" },
      { name: "Camera Activity Log", icon: Camera, route: "/caregiver/cameralogs", group: "Clinical Monitoring" },
      { name: "Task Checklist", icon: ClipboardList, route: "/caregiver/taskboard", group: "Clinical Monitoring" },
      { name: "Daily Rounds (10-Area Bedside)", icon: ClipboardCheck, route: "/caregiver/dailyrounds", group: "Clinical Monitoring" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/caregiver/documentation" },
      { name: "Care Team", icon: Stethoscope, route: "/caregiver/careteam" },
      { name: "Call Bells", icon: BellRing, route: "/caregiver/callbells" },
      { name: "Clinical Coordination", icon: Siren, route: "/caregiver/escalations" },
      { name: "Resident Profile & Care Record", icon: Users, route: "/caregiver/residents" },
      { name: "Time Clock", icon: Timer, route: "/caregiver/timeclock" },
      { name: "Shift Endorsement & Continuity", icon: Clock, route: "/caregiver/reports" },
      // Core SLMS Modules Aligned
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/caregiver/rounds" },
      { name: "Care Planning", icon: Target, route: "/caregiver/careplans" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/caregiver/medications" },
      { name: "Vaccinations", icon: Syringe, route: "/caregiver/vaccinations" },
      { name: "Resident Documents", icon: FolderOpen, route: "/caregiver/documents" },
      { name: "Medication Administration Record", icon: Pill, route: "/caregiver/mar", group: "Clinical Monitoring" },
      { name: "Incident Reports", icon: AlertTriangle, route: "/caregiver/incidents", group: "Clinical Monitoring" },
      { name: "Follow-up Tracker", icon: CalendarCheck, route: "/caregiver/followups" },
    ],
  },
  FAMILY: {
    name: "Family Sponsor",
    badge: "Family Portal",
    desc: "Monitor your relative's vitals timeline and check daily comfort summaries.",
    icon: ShieldCheck,
    profileName: "John Pendelton",
    basePath: "/family",
    footerText: "Family Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/family/dashboard" },
      { name: "Resident Profile & Care Record", icon: User, route: "/family/relative" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/family/report" },
      { name: "Care Team", icon: Stethoscope, route: "/family/careteam" },
      { name: "Care Planning", icon: Target, route: "/family/goals" },
      { name: "Alerts", icon: AlertTriangle, route: "/family/alerts" },
      { name: "Messages", icon: MessageSquare, route: "/family/messages" },
      { name: "Appointments", icon: Clock, route: "/family/appointments" },
      { name: "Transport", icon: Bus, route: "/family/transport" },
      { name: "Hotel Services", icon: ConciergeBell, route: "/family/services" },
      { name: "Community & Events", icon: CalendarDays, route: "/family/community" },
      { name: "Billing", icon: DollarSign, route: "/family/expenses" },
      // Core SLMS Modules Aligned
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/family/rounds" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/family/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/family/medications" },
      { name: "Clinical Coordination", icon: Siren, route: "/family/escalations" },
      { name: "Vaccinations", icon: Syringe, route: "/family/vaccinations" },
      { name: "Sign & Upload", icon: FolderOpen, route: "/family/forms", group: "Resident Care" },
      { name: "Follow-up Tracker", icon: CalendarCheck, route: "/family/followups" },
    ],
  },
  CARE_MANAGER: {
    name: "Care Manager",
    badge: "Clinical Oversight",
    desc: "Clinical oversight — approvals, incidents, alerts, and care coordination.",
    icon: Stethoscope,
    profileName: "Care Manager",
    basePath: "/care_manager",
    footerText: "Care Manager Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/care_manager/dashboard" },
      { name: "Alert Center", icon: BellRing, route: "/care_manager/alertcenter", group: "Clinical Monitoring" },
      { name: "Incidents", icon: AlertTriangle, route: "/care_manager/incidents", group: "Clinical Monitoring" },
      { name: "Daily Rounds (10-Area Bedside)", icon: ClipboardCheck, route: "/care_manager/dailyrounds", group: "Clinical Monitoring" },
      { name: "Clinical Coordination", icon: Siren, route: "/care_manager/escalations", group: "Clinical Monitoring" },
      { name: "Medication Approvals", icon: ClipboardCheck, route: "/care_manager/approvalworkflows", group: "Medication" },
      { name: "Medication Administration Record", icon: Pill, route: "/care_manager/mar", group: "Medication" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/care_manager/rounds", group: "Resident Care" },
      { name: "Care Planning", icon: Target, route: "/care_manager/careplans", group: "Resident Care" },
      { name: "Referrals & Appointments", icon: CalendarCheck, route: "/care_manager/referrals", group: "Resident Care" },
      { name: "Physician Comms Log", icon: MessageSquare, route: "/care_manager/physiciancomms", group: "Coordination & Comms" },
      { name: "Follow-up Tracker", icon: CalendarCheck, route: "/care_manager/followups", group: "Resident Care" },
      { name: "Consent & Move-in Forms", icon: ClipboardList, route: "/care_manager/consentforms", group: "Resident Care" },
      { name: "Clinical Reports", icon: BarChart3, route: "/care_manager/clinicalreports", group: "Administration" },
      { name: "Audit Log", icon: Shield, route: "/care_manager/auditlog", group: "Administration" },
    ],
  },
  FACILITY_ADMIN: {
    name: "Facility Admin",
    badge: "Facility Operations",
    desc: "Manage a single facility's staff, residents, and day-to-day operations.",
    icon: Building2,
    profileName: "Facility Admin",
    basePath: "/facility_admin",
    footerText: "Facility Admin Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/facility_admin/dashboard" },
      // Operations
      { name: "CRM & Leads", icon: UserPlus, route: "/facility_admin/crm" },
      { name: "Staff", icon: Users, route: "/facility_admin/staff" },
      { name: "Rooms", icon: DoorOpen, route: "/facility_admin/rooms" },
      { name: "Occupancy", icon: BedDouble, route: "/facility_admin/occupancy" },
      { name: "Purchase Requests", icon: ShoppingCart, route: "/facility_admin/purchaserequests" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/facility_admin/reports" },
      // Inventory (facility ops manages supply/medical-supply stock, not clinical MAR).
      { name: "Inventory", icon: Package, route: "/facility_admin/inventory", group: "Inventory" },
      { name: "Inventory Alerts", icon: Bell, route: "/facility_admin/inventory-alerts", group: "Inventory" },
      // Billing moved to the dedicated Billing & Finance portal (BILLING_ADMIN).
      // Dining / Diet Orders / Kitchen moved to the Nutritionist & Kitchen portals.
      // Clinical modules (Resident Care Record, Camera Log, Daily Care Doc,
      // Vaccinations, Resident Documents) live in the Care Manager / Nurse
      // portals — Facility Operations is operations-only.
      { name: "Resident Services", icon: Ticket, route: "/facility_admin/services" },
      { name: "Facility Maintenance", icon: Wrench, route: "/facility_admin/maintenance" },
      { name: "Concierge", icon: ConciergeBell, route: "/facility_admin/concierge" },
      { name: "Front Desk", icon: DoorOpen, route: "/facility_admin/frontdesk" },
      { name: "Unit Turnover", icon: Repeat, route: "/facility_admin/turnover" },
      { name: "Community & Events", icon: CalendarDays, route: "/facility_admin/community" },
    ],
  },
  BILLING_ADMIN: {
    name: "Billing & Finance",
    badge: "Finance & Billing",
    desc: "Run resident billing end-to-end — service charges, invoice generation, insurance validation, payment processing, and receipts.",
    icon: CircleDollarSign,
    profileName: "Billing & Finance Officer",
    basePath: "/billing_admin",
    footerText: "Billing & Finance Portal",
    sidebarLinks: [
      { name: "Billing Overview", icon: BarChart3, route: "/billing_admin/dashboard" },
      { name: "Transactions Ledger", icon: Wallet, route: "/billing_admin/ledger" },
      { name: "Receivables & Aging", icon: TrendingDown, route: "/billing_admin/receivables" },
      { name: "Revenue by Source", icon: PieChart, route: "/billing_admin/revenue" },
      { name: "Service Charges", icon: ClipboardList, route: "/billing_admin/charges" },
      { name: "Invoice Generation", icon: FileText, route: "/billing_admin/invoices" },
      { name: "Payment Processing", icon: CreditCard, route: "/billing_admin/payments" },
      { name: "Online Payment", icon: DollarSign, route: "/billing_admin/onlinepayment" },
      { name: "Insurance Validation", icon: ShieldCheck, route: "/billing_admin/insurance" },
      { name: "Receipts", icon: Receipt, route: "/billing_admin/receipts" },
    ],
  },
  PHYSICIAN: {
    name: "Physician",
    badge: "Medical Authority",
    desc: "Oversee the whole care team: diagnose, prescribe & sign, set care directives, answer consults, and review the patient, family, nurse & caregiver record.",
    icon: Stethoscope,
    profileName: "Dr. Alan Reyes",
    basePath: "/physician",
    footerText: "Physician Medical Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/physician/dashboard" },
      { name: "Daily Rounds (10-Area Bedside)", icon: ClipboardCheck, route: "/physician/dailyrounds" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/physician/casereview" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/physician/orders" },
      { name: "Care Planning", icon: Target, route: "/physician/careplans" },
      { name: "Consults & Referrals", icon: BookOpen, route: "/physician/consults" },
      { name: "Physician Comms Log", icon: Stethoscope, route: "/physician/physiciancomms" },
      { name: "Referrals & Appointments", icon: CalendarCheck, route: "/physician/referrals" },
      { name: "Incident Medical Review", icon: AlertTriangle, route: "/physician/incidents" },
      { name: "Clinical Coordination", icon: Siren, route: "/physician/escalations" },
      { name: "Clinical Notes", icon: PenTool, route: "/physician/notes" },
      { name: "Secure Messages", icon: MessageSquare, route: "/physician/messages" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/physician/records" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/physician/tasks" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/physician/reports" },
      { name: "Vaccinations", icon: Syringe, route: "/physician/vaccinations" },
      { name: "Resident Documents", icon: FolderOpen, route: "/physician/documents" },
      { name: "Medication Administration Record", icon: Pill, route: "/physician/mar" },
      { name: "Follow-up Tracker", icon: CalendarCheck, route: "/physician/followups" },
      { name: "Audit Log", icon: Shield, route: "/physician/auditlog" },
    ],
  },
  RESIDENT: {
    name: "Resident / Patient",
    badge: "My Care",
    desc: "View your own health timeline, daily reports, messages, and appointments.",
    icon: UserRound,
    profileName: "Arthur Pendelton",
    basePath: "/resident",
    footerText: "Resident My Care Portal",
    sidebarLinks: [
      { name: "Reporting & Care Intelligence", icon: Grid, route: "/resident/dashboard" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/resident/report" },
      { name: "Messages", icon: MessageSquare, route: "/resident/messages" },
      { name: "Appointments", icon: Clock, route: "/resident/appointments" },
      { name: "Transport", icon: Bus, route: "/resident/transport" },
      { name: "Hotel Services", icon: ConciergeBell, route: "/resident/services" },
      { name: "Community & Events", icon: CalendarDays, route: "/resident/community" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/resident/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/resident/rounds" },
      { name: "Care Planning", icon: Target, route: "/resident/careplans" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/resident/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/resident/medications" },
      { name: "Clinical Coordination", icon: Siren, route: "/resident/escalations" },
      { name: "Vaccinations", icon: Syringe, route: "/resident/vaccinations" },
      { name: "Resident Documents", icon: FolderOpen, route: "/resident/documents" },
      { name: "Clinical Reports", icon: BarChart3, route: "/resident/clinicalreports" },
    ],
  },
  FLEET_MANAGEMENT: {
    name: "Fleet Manager",
    badge: "Fleet & Transport",
    desc: "Dispatch resident transport, track live trips, and keep the vehicle fleet compliant and road-ready.",
    icon: Bus,
    profileName: "Marcus Dela Cruz",
    basePath: "/fleet_management",
    footerText: "Fleet & Transport Portal",
    sidebarLinks: [
      { name: "Fleet Dashboard", icon: Grid, route: "/fleet_management/dashboard" },
      { name: "Transport Requests", icon: ClipboardList, route: "/fleet_management/requests" },
      { name: "Ambulance Booking", icon: Ambulance, route: "/fleet_management/ambulance" },
      { name: "Trip Board", icon: Route, route: "/fleet_management/trips" },
      { name: "Vehicles", icon: Car, route: "/fleet_management/vehicles" },
      { name: "Drivers", icon: Users, route: "/fleet_management/drivers" },
      { name: "Fleet Maintenance", icon: Wrench, route: "/fleet_management/maintenance" },
      { name: "Fuel & Odometer", icon: Fuel, route: "/fleet_management/fuel" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/fleet_management/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/fleet_management/rounds" },
      { name: "Care Planning", icon: Target, route: "/fleet_management/careplans" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/fleet_management/tasks" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/fleet_management/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/fleet_management/medications" },
      { name: "Clinical Coordination", icon: Siren, route: "/fleet_management/escalations" },
    ],
  },
  DRIVER: {
    name: "Transport Driver",
    badge: "Logistics",
    desc: "Perform vehicle safety inspections, log odometer and fuel, and manage active transport requests.",
    icon: Car,
    profileName: "Eduardo Lopez",
    basePath: "/driver",
    footerText: "Driver Dispatch Portal",
    sidebarLinks: [
      { name: "Shift Dashboard", icon: Grid, route: "/driver/dashboard" },
      { name: "Trip Board", icon: Route, route: "/driver/trips" },
      { name: "Inspection Checklist", icon: ClipboardList, route: "/driver/checklist" },
      { name: "Fuel & Odometer", icon: Fuel, route: "/driver/fuel" },
      // Core SLMS Modules Aligned
      { name: "Resident Profile & Care Record", icon: ShieldCheck, route: "/driver/records" },
      { name: "Assessment & Level of Care", icon: ClipboardList, route: "/driver/rounds" },
      { name: "Care Planning", icon: Target, route: "/driver/careplans" },
      { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, route: "/driver/tasks" },
      { name: "Shift Endorsement & Continuity", icon: FileText, route: "/driver/reports" },
      { name: "Medication Management & Inventory", icon: Pill, route: "/driver/medications" },
      { name: "Clinical Coordination", icon: Siren, route: "/driver/escalations" },
    ],
  },
  SECURITY: {
    name: "Security Guard",
    badge: "Safety & Security",
    desc: "Log patrols and shift activity, file incident reports (e.g. a resident near the gate), and watch camera alerts.",
    icon: Shield,
    profileName: "Security Officer",
    basePath: "/security",
    footerText: "Security Command Portal",
    sidebarLinks: [
      { name: "Security Command", icon: Grid, route: "/security/dashboard" },
      { name: "Security & Incident Log", icon: AlertTriangle, route: "/security/securitylog" },
      { name: "Camera Activity Log", icon: Activity, route: "/security/cameralogs" },
      { name: "Time Clock", icon: Timer, route: "/security/timeclock" },
    ],
  },
  NUTRITIONIST: {
    name: "Nutritionist",
    badge: "Dietary & Nutrition",
    desc: "Set each resident's diet orders (diet type, restrictions, target meals), manage the daily menu, and review the kitchen cook list.",
    icon: Utensils,
    profileName: "Facility Nutritionist",
    basePath: "/nutritionist",
    footerText: "Nutrition & Dietary Portal",
    sidebarLinks: [
      { name: "Diet & Nutrition Orders", icon: Utensils, route: "/nutritionist/dietorders" },
      { name: "Kitchen — Cook List", icon: Grid, route: "/nutritionist/kitchen" },
      { name: "Dining & Compliance", icon: Utensils, route: "/nutritionist/dining" },
    ],
  },
  KITCHEN: {
    name: "Kitchen Staff",
    badge: "Food Service",
    desc: "See today's cook list — the active diet orders per resident, grouped by meal, so you know exactly what to prepare.",
    icon: Utensils,
    profileName: "Kitchen Staff",
    basePath: "/kitchen",
    footerText: "Kitchen Cook List Portal",
    sidebarLinks: [
      { name: "Kitchen — Cook List", icon: Utensils, route: "/kitchen/kitchen" },
    ],
  },
  HOUSEKEEPING: {
    name: "Housekeeping",
    badge: "Rooms & Cleaning",
    desc: "Work the housekeeping & laundry queue from residents, and keep room-turnover status current (make-ready → occupied).",
    icon: Sparkles,
    profileName: "Housekeeping Staff",
    basePath: "/housekeeping",
    footerText: "Housekeeping Portal",
    sidebarLinks: [
      { name: "Housekeeping Requests", icon: Sparkles, route: "/housekeeping/dashboard" },
      { name: "Unit Turnover", icon: BedDouble, route: "/housekeeping/turnover" },
    ],
  },
  MAINTENANCE: {
    name: "Maintenance",
    badge: "Repairs & Engineering",
    desc: "Work resident repair & HVAC tickets, and manage preventative facility-system maintenance schedules.",
    icon: Wrench,
    profileName: "Maintenance Staff",
    basePath: "/maintenance",
    footerText: "Maintenance Portal",
    sidebarLinks: [
      { name: "Maintenance Requests", icon: Wrench, route: "/maintenance/dashboard" },
      { name: "Facility Maintenance", icon: Wrench, route: "/maintenance/maintenance" },
    ],
  },
};

// ─────────────────────────────────────────────────────────────
// Sidebar grouping — mirrors the SLMS Feature Matrix modules so the
// nav renders as collapsible "group selections" instead of one long
// flat list. SIDEBAR_GROUP_ORDER defines the order groups appear in.
// ─────────────────────────────────────────────────────────────
export const SIDEBAR_GROUP_ORDER = [
  "Overview",
  "Clinical Monitoring",
  "Resident Care",
  "Medication",
  "Coordination & Comms",
  "Operations",
  "Inventory",
  "Billing & Finance",
  "Hospitality & Services",
  "Fleet & Transport",
  "Administration",
] as const;

export type SidebarGroup = (typeof SIDEBAR_GROUP_ORDER)[number];

const LINK_GROUP_MAP: Record<string, SidebarGroup> = {
  // Overview
  "Reporting & Care Intelligence": "Overview",
  "Fleet Dashboard": "Overview",
  "Shift Dashboard": "Overview",
  "Overview": "Overview",
  "Customer Workspaces": "Operations",
  "Plans & Entitlements": "Administration",
  "Usage & Capacity": "Operations",
  "Invitations & Access": "Administration",
  "Security & Audit": "Administration",
  "System Health": "Administration",
  "Platform Settings": "Administration",
  "Organization Overview": "Overview",
  "Communities": "Operations",
  "People & Access": "Operations",
  "Pending Approvals": "Administration",
  "Staff Invitations": "Administration",
  "Usage & Subscription": "Administration",
  "Organization Branding": "Administration",
  "Organization Audit": "Administration",
  // Resident Care (Modules 1–4)
  "Resident Profile & Care Record": "Resident Care",
  "Daily Rounds (10-Area Bedside)": "Resident Care",
  "Assessment & Level of Care": "Resident Care",
  "Care Planning": "Resident Care",
  "Daily Care Documentation & Monitoring": "Resident Care",
  "Task Assignment": "Resident Care",
  "Vaccinations": "Resident Care",
  "Resident Documents": "Resident Care",
  "Camera Activity Log": "Resident Care",
  // Guard / Security
  "Security Command": "Overview",
  "Security & Incident Log": "Operations",
  // Kitchen / Diet & Nutrition
  "Diet & Nutrition Orders": "Hospitality & Services",
  "Kitchen — Cook List": "Hospitality & Services",
  "Housekeeping Requests": "Hospitality & Services",
  "Maintenance Requests": "Hospitality & Services",
  // Medication (Module 6)
  "Medication Management & Inventory": "Medication",
  "Medication Administration Record": "Medication",
  "Orders & Prescriptions": "Medication",
  "Medication Approvals": "Medication",
  "Inventory Alerts": "Medication",
  "Physician Comms Log": "Coordination & Comms",
  "Referrals & Appointments": "Coordination & Comms",
  // Coordination & Comms (Modules 5, 7)
  "Clinical Coordination": "Coordination & Comms",
  "Care Team": "Coordination & Comms",
  "Call Bells": "Coordination & Comms",
  "Shift Endorsement & Continuity": "Coordination & Comms",
  "Consults & Referrals": "Coordination & Comms",
  "Follow-up Tracker": "Coordination & Comms",
  "Clinical Notes": "Coordination & Comms",
  "Secure Messages": "Coordination & Comms",
  "Messages": "Coordination & Comms",
  "Alerts": "Coordination & Comms",
  "Alert Center": "Clinical Monitoring",
  "Appointments": "Coordination & Comms",
  // Operations (facility, staff, incidents, billing, reports)
  "Staff Registry": "Operations",
  "Staff": "Operations",
  "Time Clock": "Operations",
  "CRM & Leads": "Operations",
  "Admissions & Registration": "Operations",
  "Rooms": "Operations",
  "Occupancy": "Operations",
  "Incidents": "Operations",
  "Incident Review": "Operations",
  "Incident Medical Review": "Operations",
  "Billing": "Operations",
  "Purchase Requests": "Operations",
  "Clinical Reports": "Operations",
  // Billing & Finance (dedicated BILLING_ADMIN portal)
  "Billing Overview": "Billing & Finance",
  "Transactions Ledger": "Billing & Finance",
  "Receivables & Aging": "Billing & Finance",
  "Revenue by Source": "Billing & Finance",
  "Service Charges": "Billing & Finance",
  "Invoice Generation": "Billing & Finance",
  "Payment Processing": "Billing & Finance",
  "Online Payment": "Billing & Finance",
  "Insurance Validation": "Billing & Finance",
  "Receipts": "Billing & Finance",
  // Hospitality & Services (Module 14 — PMS)
  "Dining & Compliance": "Hospitality & Services",
  "Resident Services": "Hospitality & Services",
  "Hotel Services": "Hospitality & Services",
  "Concierge": "Hospitality & Services",
  "Front Desk": "Hospitality & Services",
  "Unit Turnover": "Hospitality & Services",
  "Community & Events": "Hospitality & Services",
  "Facility Maintenance": "Hospitality & Services",
  "Transport": "Hospitality & Services",
  // Fleet & Transport (Module 13)
  "Transport Requests": "Fleet & Transport",
  "Ambulance Booking": "Fleet & Transport",
  "Trip Board": "Fleet & Transport",
  "Vehicles": "Fleet & Transport",
  "Drivers": "Fleet & Transport",
  "Fleet Maintenance": "Fleet & Transport",
  "Fuel & Odometer": "Fleet & Transport",
  "Inspection Checklist": "Fleet & Transport",
  // Administration (governance, system tools)
  "SLMS Feature Matrix": "Administration",
  "AI Assistant": "Administration",
  "Landing Studio": "Administration",
  "Portal Matrix": "Administration",
  "Audit Log": "Administration",
};

export const getSidebarGroup = (linkName: string): SidebarGroup =>
  LINK_GROUP_MAP[linkName] || "Overview";

/**
 * Group an ordered list of sidebar links into matrix-based sections,
 * preserving each link's original order within its group and dropping
 * any group that has no links for the current role/matrix.
 */
export const groupSidebarLinks = (
  links: SidebarLink[]
): { group: SidebarGroup; links: SidebarLink[] }[] => {
  const buckets = new Map<SidebarGroup, SidebarLink[]>();
  for (const link of links) {
    const g = link.group ?? getSidebarGroup(link.name);
    const bucket = buckets.get(g);
    if (bucket) bucket.push(link);
    else buckets.set(g, [link]);
  }
  return SIDEBAR_GROUP_ORDER.filter((g) => buckets.has(g)).map((g) => ({
    group: g,
    links: buckets.get(g)!,
  }));
};

export const getRoleDetails = (role: Role): RoleDetails => {
  return ROLES[role] || ROLES.FAMILY;
};

export const getRoleFromPath = (pathSegment: string): Role => {
  return PATH_TO_ROLE[pathSegment] || "FAMILY";
};

export const getTabName = (tabSegment: string): string => {
  return ROUTE_TO_TAB[tabSegment] || "Dashboard";
};

export interface FeatureInfo {
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  routeSegment: string;
}

export const GLOBAL_FEATURES: Record<string, FeatureInfo> = {
  "Reporting & Care Intelligence": { name: "Reporting & Care Intelligence", icon: Grid, routeSegment: "dashboard" },
  "Resident Profile & Care Record": { name: "Resident Profile & Care Record", icon: ShieldCheck, routeSegment: "records" },
  "Assessment & Level of Care": { name: "Assessment & Level of Care", icon: ClipboardList, routeSegment: "rounds" },
  "Medication Management & Inventory": { name: "Medication Management & Inventory", icon: Pill, routeSegment: "medications" },
  "Care Planning": { name: "Care Planning", icon: Target, routeSegment: "careplans" },
  "Clinical Coordination": { name: "Clinical Coordination", icon: Siren, routeSegment: "escalations" },
  "Shift Endorsement & Continuity": { name: "Shift Endorsement & Continuity", icon: FileText, routeSegment: "reports" },
  "Daily Care Documentation & Monitoring": { name: "Daily Care Documentation & Monitoring", icon: CheckCircle, routeSegment: "tasks" },
  "Admissions & Registration": { name: "Admissions & Registration", icon: UserPlus, routeSegment: "admissions" },
  "Staff Registry": { name: "Staff Registry", icon: Users, routeSegment: "staff" },
  "Staff": { name: "Staff", icon: Users, routeSegment: "staff" },
  "AI Assistant": { name: "AI Assistant", icon: Sparkles, routeSegment: "assistant" },
  "Landing Studio": { name: "Landing Studio", icon: Palette, routeSegment: "appearance" },
  "Portal Matrix": { name: "Portal Matrix", icon: ShieldCheck, routeSegment: "matrix" },
  "Incident Log": { name: "Incident Log", icon: AlertTriangle, routeSegment: "incidents" },
  "Incidents": { name: "Incidents", icon: AlertTriangle, routeSegment: "incidents" },
  "Time Clock": { name: "Time Clock", icon: Timer, routeSegment: "timeclock" },
  "Alerts": { name: "Alerts", icon: AlertTriangle, routeSegment: "alerts" },
  "Messages": { name: "Messages", icon: MessageSquare, routeSegment: "messages" },
  "Appointments": { name: "Appointments", icon: Clock, routeSegment: "appointments" },
  "Billing": { name: "Billing", icon: DollarSign, routeSegment: "billing" },
  "Expenses": { name: "Expenses", icon: DollarSign, routeSegment: "expenses" },
  "Rooms": { name: "Rooms", icon: DoorOpen, routeSegment: "rooms" },
  "Occupancy": { name: "Occupancy", icon: BedDouble, routeSegment: "occupancy" },
  "Call Bells": { name: "Call Bells", icon: BellRing, routeSegment: "callbells" },
  "Care Team": { name: "Care Team", icon: Stethoscope, routeSegment: "careteam" },
  "Transport Requests": { name: "Transport Requests", icon: ClipboardList, routeSegment: "requests" },
  "Trip Board": { name: "Trip Board", icon: Route, routeSegment: "trips" },
  "Vehicles": { name: "Vehicles", icon: Car, routeSegment: "vehicles" },
  "Drivers": { name: "Drivers", icon: Users, routeSegment: "drivers" },
  "Fleet Maintenance": { name: "Fleet Maintenance", icon: Wrench, routeSegment: "maintenance" },
  "Fuel & Odometer": { name: "Fuel & Odometer", icon: Fuel, routeSegment: "fuel" },
  "Transport": { name: "Transport", icon: Bus, routeSegment: "transport" },
  "Dining & Compliance": { name: "Dining & Compliance", icon: Utensils, routeSegment: "dining" },
  "Resident Services": { name: "Resident Services", icon: Ticket, routeSegment: "services" },
  "Concierge": { name: "Concierge", icon: ConciergeBell, routeSegment: "concierge" },
  "Hotel Services": { name: "Hotel Services", icon: ConciergeBell, routeSegment: "services" },
  "Front Desk": { name: "Front Desk", icon: DoorOpen, routeSegment: "frontdesk" },
  "Unit Turnover": { name: "Unit Turnover", icon: Repeat, routeSegment: "turnover" },
  "Community & Events": { name: "Community & Events", icon: CalendarDays, routeSegment: "community" },
  "Orders & Prescriptions": { name: "Orders & Prescriptions", icon: Pill, routeSegment: "orders" },
  "Clinical Notes": { name: "Clinical Notes", icon: PenTool, routeSegment: "notes" },
  "Incident Review": { name: "Incident Review", icon: AlertTriangle, routeSegment: "incidents" },
  "Secure Messages": { name: "Secure Messages", icon: MessageSquare, routeSegment: "messages" },
  "Case Review": { name: "Case Review", icon: ClipboardList, routeSegment: "casereview" },
  "Consults & Referrals": { name: "Consults & Referrals", icon: BookOpen, routeSegment: "consults" },
  "Incident Medical Review": { name: "Incident Medical Review", icon: AlertTriangle, routeSegment: "incidents" },
  "Vaccinations": { name: "Vaccinations", icon: Syringe, routeSegment: "vaccinations" },
  "Resident Documents": { name: "Resident Documents", icon: FolderOpen, routeSegment: "documents" },
  "Medication Administration Record": { name: "Medication Administration Record", icon: Pill, routeSegment: "mar" },
  "Follow-up Tracker": { name: "Follow-up Tracker", icon: CalendarCheck, routeSegment: "followups" },
  "Audit Log": { name: "Audit Log", icon: Shield, routeSegment: "auditlog" },
  "Inventory Alerts": { name: "Inventory Alerts", icon: Bell, routeSegment: "inventory-alerts" },
  "Clinical Reports": { name: "Clinical Reports", icon: BarChart3, routeSegment: "clinicalreports" },
  "Daily Rounds (10-Area Bedside)": { name: "Daily Rounds (10-Area Bedside)", icon: ClipboardCheck, routeSegment: "dailyrounds" },
  "SLMS Feature Matrix": { name: "SLMS Feature Matrix", icon: ShieldCheck, routeSegment: "featurematrix" },
};
