"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { Activity, Building2, CheckCircle2, ClipboardCheck, CreditCard, DollarSign, ExternalLink, Gauge, Loader2, Mail, Palette, Plus, Receipt, RefreshCw, Shield, UserPlus, Users, Wallet, XCircle } from "lucide-react";

type Community = { id: string; name: string; code?: string | null; timezone: string; isActive: boolean; bedsTotal?: number | null; _count: { residents: number; staff: number } };
type Member = { id: string; role: string; status: string; user: { id: string; name: string; email: string; isActive: boolean; lastLogin?: string | null; communityMemberships: { id: string; role: string; status: string; community: { id: string; name: string } }[] } };
type Invitation = { id: string; email: string; status: string; organizationRole?: string | null; communityRole?: string | null; expiresAt: string; createdAt: string; community?: { id: string; name: string } | null };
type Staff = { id: string; position: string; department?: string | null; isActive: boolean; isApproved: boolean; community?: { id: string; name: string } | null; user: { id: string; name: string; email: string; phone?: string | null; role: string; isActive: boolean } };
type AuditEvent = { id: string; actorName: string; actorRole: string; action: string; entityType: string; reason?: string | null; createdAt: string };
type Organization = { id: string; name: string; logoUrl?: string | null; primaryColor?: string | null; secondaryColor?: string | null; emailFromName?: string | null; status: string; communities: Community[]; memberships: Member[]; invitations: Invitation[]; staff: Staff[]; subscription?: { status: string; startsAt?: string | null; trialEndsAt?: string | null; currentPeriodEnd?: string | null; nextBillingDate?: string | null; plan: { name: string; key: string; priceMonthly?: number | null; currency?: string | null; maxCommunities?: number | null; maxActiveResidents?: number | null; maxStaffSeats?: number | null; entitlements: { id: string; featureKey: string; enabled: boolean }[] } } | null };

function Card({ title, subtitle, icon, children, action }: { title: string; subtitle?: string; icon: ReactNode; children: ReactNode; action?: ReactNode }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600">{icon}</span><div><h2 className="font-bold text-slate-900">{title}</h2>{subtitle && <p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div></div>{action}</div><div className="mt-4">{children}</div></section>;
}
function Badge({ value }: { value: string }) { const good = ["ACTIVE", "APPROVED", "ACCEPTED", "TRIALING"].includes(value); const pending = ["PENDING", "INVITED"].includes(value); return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${good ? "bg-emerald-100 text-emerald-700" : pending ? "bg-amber-100 text-amber-700" : "bg-rose-100 text-rose-700"}`}>{value.replaceAll("_", " ")}</span>; }
function Stat({ label, value, icon }: { label: string; value: number | string; icon: ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="inline-flex rounded-lg bg-blue-50 p-2 text-blue-600">{icon}</span><b className="mt-3 block text-2xl text-slate-900">{value}</b><span className="text-xs text-slate-500">{label}</span></div>; }
function communityAccess(member: Member, communities: Community[]) {
  const assigned = member.user.communityMemberships.filter((item) => item.status === "ACTIVE").map((item) => `${item.community.name} (${item.role.replaceAll("_", " ")})`);
  if (assigned.length) return assigned.join(", ");
  if (["OWNER", "ADMIN"].includes(member.role)) return `All communities: ${communities.map((community) => community.name).join(", ") || "none created"}`;
  return "No community assignment";
}

export default function OrganizationAdminPortalContent({ tab = "dashboard" }: { tab?: string }) {
  const [organization, setOrganization] = useState<Organization | null>(null);
  const [auditEvents, setAuditEvents] = useState<AuditEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  type Billing = { planName: string | null; status: string; amountDue: number | null; currency: string; dueDate: string | null; paidThisPeriod: boolean; onlinePaymentEnabled: boolean; payments: { id: string; amount: number; currency: string; method: string; provider: string; status: string; periodLabel: string; paidAt: string }[] };
  const [billing, setBilling] = useState<Billing | null>(null);
  const [payMethod, setPayMethod] = useState("CARD");
  const [paying, setPaying] = useState(false);

  async function load() {
    setLoading(true); setError("");
    const response = await fetch("/api/organization-admin/overview", { cache: "no-store" });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) setError(body.code === "MFA_REQUIRED" ? "Organization owners and admins must verify MFA. Open Account Settings → Authenticator MFA, then retry." : body.error || "Unable to load organization administration data");
    else { setOrganization(body.organization); setAuditEvents(body.auditEvents || []); }
    setLoading(false);
  }
  useEffect(() => { let cancelled = false; void fetch("/api/organization-admin/overview", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (cancelled) return; if (!response.ok) throw new Error(body.code === "MFA_REQUIRED" ? "Organization owners and admins must verify MFA. Open Account Settings → Authenticator MFA, then retry." : body.error || "Unable to load organization administration data"); setOrganization(body.organization); setAuditEvents(body.auditEvents || []); }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Unable to load organization administration data"); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { let cancelled = false; void fetch("/api/organization-admin/billing", { cache: "no-store" }).then((response) => (response.ok ? response.json() : null)).then((data) => { if (!cancelled && data) setBilling(data); }).catch(() => {}); return () => { cancelled = true; }; }, []);

  const totals = useMemo(() => (organization?.communities || []).reduce((sum, community) => ({ residents: sum.residents + community._count.residents, staff: sum.staff + community._count.staff }), { residents: 0, staff: 0 }), [organization]);
  const pendingStaff = (organization?.staff || []).filter((staff) => !staff.isApproved);
  const pendingInvitations = (organization?.invitations || []).filter((invitation) => invitation.status === "PENDING");

  async function createCommunity(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); setError("");
    const response = await fetch("/api/organization-admin/communities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data.entries())) });
    const body = await response.json(); if (response.ok) { form.reset(); await load(); } else setError(body.error || "Community creation failed"); setBusy(false);
  }
  async function createStaffAccount(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!organization) return; const form = event.currentTarget; const data = new FormData(form); const email = String(data.get("email") || ""); setBusy(true); setError(""); setNotice("");
    const response = await fetch(`/api/organization-admin/staff-accounts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), email, password: data.get("password"), phone: data.get("phone"), position: data.get("position"), department: data.get("department"), communityId: data.get("communityId"), role: data.get("role") }) });
    const body = await response.json().catch(() => ({})); if (response.ok) { form.reset(); setNotice(`Account created for ${email}. Share the email and initial password so they can sign in.`); await load(); } else setError(body.error || "Account creation failed"); setBusy(false);
  }
  async function decideStaff(id: string, status: "APPROVED" | "REJECTED") { setBusy(true); const response = await fetch(`/api/organization-admin/staff/${id}/approval`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const body = await response.json(); if (response.ok) await load(); else setError(body.error || "Approval failed"); setBusy(false); }
  async function refreshBilling() { try { const response = await fetch("/api/organization-admin/billing", { cache: "no-store" }); if (response.ok) setBilling(await response.json()); } catch { /* non-fatal */ } }
  async function payNow() {
    setPaying(true); setError(""); setNotice("");
    const response = await fetch("/api/organization-admin/billing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ method: payMethod }) });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) { setError(body.error || "Payment failed"); setPaying(false); return; }
    if (body.checkoutUrl) { window.location.href = body.checkoutUrl; return; }
    setNotice(body.simulated ? "Payment recorded. No live payment gateway is configured, so this was processed in demo mode." : "Payment successful.");
    await Promise.all([load(), refreshBilling()]);
    setPaying(false);
  }
  async function saveBranding(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!organization) return; const data = new FormData(event.currentTarget); setBusy(true); const response = await fetch(`/api/organizations/${organization.id}/branding`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data.entries())) }); const body = await response.json(); if (response.ok) await load(); else setError(body.error || "Branding update failed"); setBusy(false); }

  const overview = <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Communities" value={organization?.communities.length || 0} icon={<Building2 className="h-5 w-5"/>}/><Stat label="Active residents" value={totals.residents} icon={<Activity className="h-5 w-5"/>}/><Stat label="Staff profiles" value={totals.staff} icon={<Users className="h-5 w-5"/>}/><Stat label="Pending invitations" value={pendingInvitations.length} icon={<Mail className="h-5 w-5"/>}/></div><Card title="Organization control center" subtitle="Manage company-wide access here, then enter a community for clinical and facility operations." icon={<Shield className="h-5 w-5"/>} action={<Link href="/facility_admin/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Open Facility Operations <ExternalLink className="h-4 w-4"/></Link>}><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><b className="text-sm">Subscription</b><p className="mt-1 text-xs text-slate-500">{organization?.subscription?.plan.name || "No plan"} · {organization?.subscription?.status || "UNASSIGNED"}</p></div><div className="rounded-xl bg-slate-50 p-4"><b className="text-sm">People with access</b><p className="mt-1 text-xs text-slate-500">{organization?.memberships.filter((item) => item.status === "ACTIVE").length || 0} active organization memberships</p></div><div className="rounded-xl bg-slate-50 p-4"><b className="text-sm">Approval queue</b><p className="mt-1 text-xs text-slate-500">{pendingStaff.length} staff records awaiting review</p></div></div></Card></div>;

  const communities = <div className="space-y-5"><Card title="Add community" subtitle="New facilities are limited by the assigned subscription plan." icon={<Plus className="h-5 w-5"/>}><form onSubmit={createCommunity} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input required name="name" placeholder="Community name" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="code" placeholder="Community code" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="timezone" defaultValue="America/New_York" placeholder="Timezone" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="bedsTotal" type="number" min="1" placeholder="Bed capacity" className="rounded-xl border px-3 py-2.5 text-sm"/><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Create community</button></form></Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{organization?.communities.map((community) => <article key={community.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><div><h3 className="font-bold">{community.name}</h3><p className="text-xs text-slate-500">{community.code || "No code"} · {community.timezone}</p></div><Badge value={community.isActive ? "ACTIVE" : "SUSPENDED"}/></div><div className="mt-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-slate-50 p-2"><b className="block">{community._count.residents}</b>Residents</span><span className="rounded-lg bg-slate-50 p-2"><b className="block">{community._count.staff}</b>Staff</span><span className="rounded-lg bg-slate-50 p-2"><b className="block">{community.bedsTotal ?? "—"}</b>Beds</span></div></article>)}</div></div>;

  const people = <Card title="People and access" subtitle="Organization and community memberships. Owners and organization admins automatically cover every community." icon={<Users className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Person</th><th className="p-3">Organization role</th><th className="p-3">Community access</th><th className="p-3">Status</th><th className="p-3">Last login</th></tr></thead><tbody>{organization?.memberships.map((membership) => <tr key={membership.id} className="border-b last:border-0"><td className="p-3"><b className="block">{membership.user.name}</b><span className="text-xs text-slate-500">{membership.user.email}</span></td><td className="p-3">{membership.role}</td><td className="p-3 text-xs">{communityAccess(membership, organization.communities)}</td><td className="p-3"><Badge value={membership.status}/></td><td className="p-3 text-xs text-slate-500">{membership.user.lastLogin ? new Date(membership.user.lastLogin).toLocaleString() : "Never"}</td></tr>)}</tbody></table></div></Card>;

  const ACCOUNT_ROLES: [string, string][] = [["FACILITY_ADMIN", "Facility Admin"], ["CARE_MANAGER", "Care Manager"], ["SUPERADMIN", "Super Admin"]];
  const roleLabel = (value: string) => ACCOUNT_ROLES.find(([key]) => key === value)?.[1] || value.replaceAll("_", " ");
  const leadershipStaff = (organization?.staff || []).filter((staff) => ACCOUNT_ROLES.some(([key]) => key === staff.user.role));
  const staffAccountForm = <Card title="Add staff account" subtitle="Create a login for an administrator or manager. The account works immediately with the initial password you set — no email invitation is sent." icon={<UserPlus className="h-5 w-5"/>}><form onSubmit={createStaffAccount} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input required name="name" placeholder="Full name" className="rounded-xl border px-3 py-2.5 text-sm"/><input required type="email" name="email" placeholder="Work email" className="rounded-xl border px-3 py-2.5 text-sm"/><input required type="password" name="password" minLength={8} placeholder="Initial password (min 8)" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="phone" placeholder="Phone" className="rounded-xl border px-3 py-2.5 text-sm"/><input required name="position" placeholder="Position/title" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="department" placeholder="Department" className="rounded-xl border px-3 py-2.5 text-sm"/><select required name="communityId" className="rounded-xl border px-3 py-2.5 text-sm"><option value="">Select community</option>{organization?.communities.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required name="role" className="rounded-xl border px-3 py-2.5 text-sm"><option value="">Select role</option>{ACCOUNT_ROLES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white xl:col-span-2">Create account</button></form></Card>;
  const invitations = <div className="space-y-5">{staffAccountForm}<Card title="Administrators & managers" subtitle="Leadership accounts you have created for this organization." icon={<Users className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Person</th><th className="p-3">Role</th><th className="p-3">Community</th><th className="p-3">Position</th><th className="p-3">Status</th></tr></thead><tbody>{leadershipStaff.map((staff) => <tr key={staff.id} className="border-b last:border-0"><td className="p-3"><b className="block">{staff.user.name}</b><span className="text-xs text-slate-500">{staff.user.email}</span></td><td className="p-3">{roleLabel(staff.user.role)}</td><td className="p-3 text-xs">{staff.community?.name || "—"}</td><td className="p-3 text-xs">{staff.position}</td><td className="p-3"><Badge value={staff.isApproved ? (staff.user.isActive ? "ACTIVE" : "SUSPENDED") : "PENDING"}/></td></tr>)}</tbody></table>{!leadershipStaff.length && <p className="text-sm text-slate-500">No administrator or manager accounts yet.</p>}</div></Card></div>;

  const approvals = <Card title="Pending staff approvals" subtitle="Approve or reject staff records submitted through delegated facility workflows." icon={<ClipboardCheck className="h-5 w-5"/>}><div className="space-y-2">{pendingStaff.map((staff) => <div key={staff.id} className="flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-sm">{staff.user.name}</b><p className="text-xs text-slate-500">{staff.position} · {staff.community?.name || "Unassigned"} · {staff.user.email}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => void decideStaff(staff.id, "APPROVED")} className="inline-flex items-center gap-1 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Approve</button><button disabled={busy} onClick={() => void decideStaff(staff.id, "REJECTED")} className="inline-flex items-center gap-1 rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700"><XCircle className="h-4 w-4"/>Reject</button></div></div>)}{!pendingStaff.length && <p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">No staff records are waiting for approval.</p>}</div></Card>;

  const plan = organization?.subscription?.plan;
  const sub = organization?.subscription;
  const priceMonthly = plan?.priceMonthly ?? null;
  const currency = plan?.currency || "PHP";
  const fmtMoney = (amount: number) => { try { return new Intl.NumberFormat("en-PH", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount); } catch { return `${currency} ${amount.toLocaleString()}`; } };
  const billingDate = sub?.nextBillingDate || sub?.currentPeriodEnd || sub?.trialEndsAt || null;
  const billingLabel = sub?.status === "TRIALING" ? "Trial ends" : "Next billing";
  const subscription = <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Stat label={`Communities / ${plan?.maxCommunities ?? "∞"}`} value={organization?.communities.filter((item) => item.isActive).length || 0} icon={<Building2 className="h-5 w-5"/>}/><Stat label={`Residents / ${plan?.maxActiveResidents ?? "∞"}`} value={totals.residents} icon={<Activity className="h-5 w-5"/>}/><Stat label={`Staff / ${plan?.maxStaffSeats ?? "∞"}`} value={totals.staff} icon={<Users className="h-5 w-5"/>}/></div>
    <div className="grid gap-3 lg:grid-cols-2">
      <Card title="Monthly payment" subtitle="Your current recurring subscription charge." icon={<DollarSign className="h-5 w-5"/>}>
        <div className="rounded-2xl bg-gradient-to-r from-blue-600 to-indigo-600 p-5 text-white">
          {priceMonthly !== null ? <div className="flex items-baseline gap-1.5"><span className="text-3xl font-black">{fmtMoney(priceMonthly)}</span><span className="text-sm text-blue-100">/ month</span></div> : <span className="text-2xl font-bold">Custom pricing</span>}
          <p className="mt-2 text-xs text-blue-100">{plan?.name || "No plan assigned"} · {sub?.status || "UNASSIGNED"}</p>
          {billingDate && <p className="mt-1 text-xs text-blue-100">{billingLabel}: {new Date(billingDate).toLocaleDateString()}</p>}
        </div>
        {priceMonthly === null && <p className="mt-3 text-xs text-slate-500">Your plan does not have a listed price yet. Contact the SLMS Platform Administrator for billing details.</p>}
      </Card>
      <Card title="Subscription" subtitle="Plan changes are handled by the SLMS Platform Administrator." icon={<Gauge className="h-5 w-5"/>}>
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div><b>{plan?.name || "No plan assigned"}</b><p className="text-xs text-slate-500">{plan?.key} · {plan?.entitlements.filter((item) => item.enabled).length || 0} enabled module entitlements</p></div><Badge value={sub?.status || "UNASSIGNED"}/></div>
        <div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl border p-3"><span className="text-slate-500">Started</span><b className="mt-0.5 block text-slate-900">{sub?.startsAt ? new Date(sub.startsAt).toLocaleDateString() : "—"}</b></div><div className="rounded-xl border p-3"><span className="text-slate-500">{billingLabel}</span><b className="mt-0.5 block text-slate-900">{billingDate ? new Date(billingDate).toLocaleDateString() : "—"}</b></div></div>
      </Card>
    </div>
    <div className="grid gap-3 lg:grid-cols-2">
      <Card title="Payment options" subtitle="Pay your monthly subscription securely." icon={<CreditCard className="h-5 w-5"/>}>
        {billing?.amountDue != null ? <><p className="mb-2 text-xs font-semibold text-slate-500">Choose a payment method</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{([["CARD", "Credit / Debit"], ["GCASH", "GCash"], ["MAYA", "Maya"], ["BANK_TRANSFER", "Bank Transfer"]] as [string, string][]).map(([value, label]) => <button key={value} type="button" onClick={() => setPayMethod(value)} className={`rounded-xl border px-3 py-2.5 text-xs font-semibold transition ${payMethod === value ? "border-blue-500 bg-blue-50 text-blue-700" : "border-slate-200 text-slate-600 hover:border-blue-300"}`}>{label}</button>)}</div><button disabled={paying || billing.paidThisPeriod} onClick={() => void payNow()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white transition hover:bg-emerald-700 disabled:opacity-50">{paying && <Loader2 className="h-4 w-4 animate-spin"/>}{billing.paidThisPeriod ? "Paid for this period" : `Pay ${fmtMoney(billing.amountDue)}`}</button><p className="mt-2 text-[11px] text-slate-400">Secured checkout. When a payment provider is configured you are redirected to complete payment; otherwise it is recorded in demo mode.</p></> : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Online payment becomes available once your plan has a price. Contact the SLMS Platform Administrator.</p>}
      </Card>
      <Card title="Payment history" subtitle="Your recent subscription payments." icon={<Receipt className="h-5 w-5"/>}>
        <div className="space-y-2">{billing?.payments?.length ? billing.payments.map((payment) => { const money = (() => { try { return new Intl.NumberFormat("en-PH", { style: "currency", currency: payment.currency, maximumFractionDigits: 0 }).format(payment.amount); } catch { return `${payment.currency} ${payment.amount.toLocaleString()}`; } })(); return <div key={payment.id} className="flex items-center justify-between gap-3 rounded-xl border p-3 text-sm"><div><b className="text-slate-900">{money}</b><p className="text-xs text-slate-500">{new Date(payment.paidAt).toLocaleDateString()} · {payment.method.replaceAll("_", " ")} · {payment.provider}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${payment.status === "PAID" ? "bg-emerald-100 text-emerald-700" : payment.status === "PENDING" ? "bg-amber-100 text-amber-700" : "bg-rose-100 text-rose-700"}`}>{payment.status}</span></div>; }) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No payments yet.</p>}</div>
      </Card>
    </div>
    <Card title="Usage this period" subtitle="Current consumption against your plan's included capacity." icon={<Wallet className="h-5 w-5"/>}>
      <div className="space-y-3">{[{ label: "Communities", used: organization?.communities.filter((item) => item.isActive).length || 0, limit: plan?.maxCommunities }, { label: "Active residents", used: totals.residents, limit: plan?.maxActiveResidents }, { label: "Staff seats", used: totals.staff, limit: plan?.maxStaffSeats }].map((row) => { const pct = row.limit ? Math.min(100, Math.round((row.used / row.limit) * 100)) : 0; return <div key={row.label}><div className="flex items-center justify-between text-xs"><span className="font-semibold text-slate-700">{row.label}</span><span className="text-slate-500">{row.used} / {row.limit ?? "∞"}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${pct >= 90 ? "bg-rose-500" : pct >= 70 ? "bg-amber-500" : "bg-emerald-500"}`} style={{ width: `${row.limit ? pct : 6}%` }}/></div></div>; })}</div>
    </Card>
  </div>;

  const branding = <Card title="Organization branding" subtitle="These values apply across authorized organization and community experiences." icon={<Palette className="h-5 w-5"/>}><form onSubmit={saveBranding} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Logo URL<input name="logoUrl" defaultValue={organization?.logoUrl || ""} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-medium">Email sender name<input name="emailFromName" defaultValue={organization?.emailFromName || organization?.name || ""} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-medium">Primary color<input name="primaryColor" type="color" defaultValue={organization?.primaryColor || "#2563eb"} className="mt-2 h-11 w-full rounded-xl border p-1"/></label><label className="text-sm font-medium">Secondary color<input name="secondaryColor" type="color" defaultValue={organization?.secondaryColor || "#4f46e5"} className="mt-2 h-11 w-full rounded-xl border p-1"/></label><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white sm:col-span-2">Save branding</button></form></Card>;
  const audit = <Card title="Organization audit" subtitle="Sensitive operational actions recorded for this customer tenant." icon={<Shield className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Time</th><th className="p-3">Actor</th><th className="p-3">Action</th><th className="p-3">Target</th><th className="p-3">Reason</th></tr></thead><tbody>{auditEvents.map((event) => <tr key={event.id} className="border-b last:border-0"><td className="p-3 text-xs">{new Date(event.createdAt).toLocaleString()}</td><td className="p-3"><b className="block">{event.actorName}</b><span className="text-xs text-slate-500">{event.actorRole}</span></td><td className="p-3">{event.action}</td><td className="p-3">{event.entityType}</td><td className="p-3 text-xs text-slate-500">{event.reason || "—"}</td></tr>)}</tbody></table></div></Card>;

  const views: Record<string, ReactNode> = { dashboard: overview, communities, people, approvals, invitations, subscription, branding, audit };
  return <div className="space-y-6"><section className="rounded-2xl bg-gradient-to-r from-blue-700 to-indigo-700 p-5 text-white shadow-lg"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-100">SLMS Customer Administration</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{organization?.name || "Organization Admin Portal"}</h1><p className="mt-2 text-sm text-blue-100">Manage communities, people, invitations, access, subscription usage, branding, and tenant security.</p></div>{loading && <Loader2 className="h-5 w-5 animate-spin"/>}</div></section>{error && <div className="flex flex-col gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 sm:flex-row sm:items-center sm:justify-between"><span>{error}</span><button onClick={() => void load()} className="inline-flex items-center justify-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Retry</button></div>}{notice && <div className="flex items-center justify-between gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700"><span>{notice}</span><button onClick={() => setNotice("")} className="rounded-lg border bg-white px-3 py-1.5 text-xs font-bold">Dismiss</button></div>}{organization ? views[tab] || overview : !loading && !error ? <p className="text-sm text-slate-500">Organization data is unavailable.</p> : null}</div>;
}
