"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { Activity, Building2, CheckCircle2, ClipboardCheck, ExternalLink, Gauge, Loader2, Mail, Palette, Plus, RefreshCw, Shield, Users, XCircle } from "lucide-react";

type Community = { id: string; name: string; code?: string | null; timezone: string; isActive: boolean; bedsTotal?: number | null; _count: { residents: number; staff: number } };
type Member = { id: string; role: string; status: string; user: { id: string; name: string; email: string; isActive: boolean; lastLogin?: string | null; communityMemberships: { id: string; role: string; status: string; community: { id: string; name: string } }[] } };
type Invitation = { id: string; email: string; status: string; organizationRole?: string | null; communityRole?: string | null; expiresAt: string; createdAt: string; community?: { id: string; name: string } | null };
type Staff = { id: string; position: string; department?: string | null; isActive: boolean; isApproved: boolean; community?: { id: string; name: string } | null; user: { id: string; name: string; email: string; phone?: string | null; role: string; isActive: boolean } };
type AuditEvent = { id: string; actorName: string; actorRole: string; action: string; entityType: string; reason?: string | null; createdAt: string };
type Organization = { id: string; name: string; logoUrl?: string | null; primaryColor?: string | null; secondaryColor?: string | null; emailFromName?: string | null; status: string; communities: Community[]; memberships: Member[]; invitations: Invitation[]; staff: Staff[]; subscription?: { status: string; plan: { name: string; key: string; maxCommunities?: number | null; maxActiveResidents?: number | null; maxStaffSeats?: number | null; entitlements: { id: string; featureKey: string; enabled: boolean }[] } } | null };

function Card({ title, subtitle, icon, children, action }: { title: string; subtitle?: string; icon: ReactNode; children: ReactNode; action?: ReactNode }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600">{icon}</span><div><h2 className="font-bold text-slate-900">{title}</h2>{subtitle && <p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div></div>{action}</div><div className="mt-4">{children}</div></section>;
}
function Badge({ value }: { value: string }) { const good = ["ACTIVE", "APPROVED", "ACCEPTED", "TRIALING"].includes(value); const pending = ["PENDING", "INVITED"].includes(value); return <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${good ? "bg-emerald-100 text-emerald-700" : pending ? "bg-amber-100 text-amber-700" : "bg-rose-100 text-rose-700"}`}>{value.replaceAll("_", " ")}</span>; }
function Stat({ label, value, icon }: { label: string; value: number | string; icon: ReactNode }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="inline-flex rounded-lg bg-blue-50 p-2 text-blue-600">{icon}</span><b className="mt-3 block text-2xl text-slate-900">{value}</b><span className="text-xs text-slate-500">{label}</span></div>; }
function communityAccess(member: Member, communities: Community[]) {
  const assigned = member.user.communityMemberships.filter((item) => item.status === "ACTIVE").map((item) => `${item.community.name} (${item.role.replaceAll("_", " ")})`);
  if (assigned.length) return assigned.join(", ");
  if (["OWNER", "ADMIN"].includes(member.role)) return `All communities: ${communities.map((community) => community.name).join(", ") || "none created"}`;
  return "No community assignment";
}

export default function OrganizationAdminPortalContent({ tab = "dashboard" }: { tab?: string }) {
  const [organization, setOrganization] = useState<Organization | null>(null);
  const [auditEvents, setAuditEvents] = useState<AuditEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  async function load() {
    setLoading(true); setError("");
    const response = await fetch("/api/organization-admin/overview", { cache: "no-store" });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) setError(body.code === "MFA_REQUIRED" ? "Organization owners and admins must verify MFA. Open Account Settings → Authenticator MFA, then retry." : body.error || "Unable to load organization administration data");
    else { setOrganization(body.organization); setAuditEvents(body.auditEvents || []); }
    setLoading(false);
  }
  useEffect(() => { let cancelled = false; void fetch("/api/organization-admin/overview", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (cancelled) return; if (!response.ok) throw new Error(body.code === "MFA_REQUIRED" ? "Organization owners and admins must verify MFA. Open Account Settings → Authenticator MFA, then retry." : body.error || "Unable to load organization administration data"); setOrganization(body.organization); setAuditEvents(body.auditEvents || []); }).catch((cause) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Unable to load organization administration data"); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);

  const totals = useMemo(() => (organization?.communities || []).reduce((sum, community) => ({ residents: sum.residents + community._count.residents, staff: sum.staff + community._count.staff }), { residents: 0, staff: 0 }), [organization]);
  const pendingStaff = (organization?.staff || []).filter((staff) => !staff.isApproved);
  const pendingInvitations = (organization?.invitations || []).filter((invitation) => invitation.status === "PENDING");

  async function createCommunity(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); setError("");
    const response = await fetch("/api/organization-admin/communities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data.entries())) });
    const body = await response.json(); if (response.ok) { form.reset(); await load(); } else setError(body.error || "Community creation failed"); setBusy(false);
  }
  async function inviteStaff(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!organization) return; const form = event.currentTarget; const data = new FormData(form); setBusy(true); setError("");
    const response = await fetch(`/api/organizations/${organization.id}/invitations`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), email: data.get("email"), phone: data.get("phone"), position: data.get("position"), department: data.get("department"), communityId: data.get("communityId"), communityRole: data.get("communityRole") }) });
    const body = await response.json(); if (response.ok) { form.reset(); await load(); } else setError(body.error || "Staff invitation failed"); setBusy(false);
  }
  async function decideStaff(id: string, status: "APPROVED" | "REJECTED") { setBusy(true); const response = await fetch(`/api/organization-admin/staff/${id}/approval`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const body = await response.json(); if (response.ok) await load(); else setError(body.error || "Approval failed"); setBusy(false); }
  async function revokeInvitation(id: string) { setBusy(true); const response = await fetch(`/api/organization-admin/invitations/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "REVOKED" }) }); const body = await response.json(); if (response.ok) await load(); else setError(body.error || "Revocation failed"); setBusy(false); }
  async function saveBranding(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!organization) return; const data = new FormData(event.currentTarget); setBusy(true); const response = await fetch(`/api/organizations/${organization.id}/branding`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data.entries())) }); const body = await response.json(); if (response.ok) await load(); else setError(body.error || "Branding update failed"); setBusy(false); }

  const overview = <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Communities" value={organization?.communities.length || 0} icon={<Building2 className="h-5 w-5"/>}/><Stat label="Active residents" value={totals.residents} icon={<Activity className="h-5 w-5"/>}/><Stat label="Staff profiles" value={totals.staff} icon={<Users className="h-5 w-5"/>}/><Stat label="Pending invitations" value={pendingInvitations.length} icon={<Mail className="h-5 w-5"/>}/></div><Card title="Organization control center" subtitle="Manage company-wide access here, then enter a community for clinical and facility operations." icon={<Shield className="h-5 w-5"/>} action={<Link href="/facility_admin/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Open Facility Operations <ExternalLink className="h-4 w-4"/></Link>}><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><b className="text-sm">Subscription</b><p className="mt-1 text-xs text-slate-500">{organization?.subscription?.plan.name || "No plan"} · {organization?.subscription?.status || "UNASSIGNED"}</p></div><div className="rounded-xl bg-slate-50 p-4"><b className="text-sm">People with access</b><p className="mt-1 text-xs text-slate-500">{organization?.memberships.filter((item) => item.status === "ACTIVE").length || 0} active organization memberships</p></div><div className="rounded-xl bg-slate-50 p-4"><b className="text-sm">Approval queue</b><p className="mt-1 text-xs text-slate-500">{pendingStaff.length} staff records awaiting review</p></div></div></Card></div>;

  const communities = <div className="space-y-5"><Card title="Add community" subtitle="New facilities are limited by the assigned subscription plan." icon={<Plus className="h-5 w-5"/>}><form onSubmit={createCommunity} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input required name="name" placeholder="Community name" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="code" placeholder="Community code" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="timezone" defaultValue="America/New_York" placeholder="Timezone" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="bedsTotal" type="number" min="1" placeholder="Bed capacity" className="rounded-xl border px-3 py-2.5 text-sm"/><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Create community</button></form></Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{organization?.communities.map((community) => <article key={community.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><div><h3 className="font-bold">{community.name}</h3><p className="text-xs text-slate-500">{community.code || "No code"} · {community.timezone}</p></div><Badge value={community.isActive ? "ACTIVE" : "SUSPENDED"}/></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-slate-50 p-2"><b className="block">{community._count.residents}</b>Residents</span><span className="rounded-lg bg-slate-50 p-2"><b className="block">{community._count.staff}</b>Staff</span><span className="rounded-lg bg-slate-50 p-2"><b className="block">{community.bedsTotal ?? "—"}</b>Beds</span></div></article>)}</div></div>;

  const people = <Card title="People and access" subtitle="Organization and community memberships. Owners and organization admins automatically cover every community." icon={<Users className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Person</th><th className="p-3">Organization role</th><th className="p-3">Community access</th><th className="p-3">Status</th><th className="p-3">Last login</th></tr></thead><tbody>{organization?.memberships.map((membership) => <tr key={membership.id} className="border-b last:border-0"><td className="p-3"><b className="block">{membership.user.name}</b><span className="text-xs text-slate-500">{membership.user.email}</span></td><td className="p-3">{membership.role}</td><td className="p-3 text-xs">{communityAccess(membership, organization.communities)}</td><td className="p-3"><Badge value={membership.status}/></td><td className="p-3 text-xs text-slate-500">{membership.user.lastLogin ? new Date(membership.user.lastLogin).toLocaleString() : "Never"}</td></tr>)}</tbody></table></div></Card>;

  const invitationForm = <Card title="Invite staff account" subtitle="The owner approves the role here; Supabase sends the recipient a secure account invitation." icon={<Mail className="h-5 w-5"/>}><form onSubmit={inviteStaff} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input required name="name" placeholder="Full name" className="rounded-xl border px-3 py-2.5 text-sm"/><input required type="email" name="email" placeholder="Work email" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="phone" placeholder="Phone" className="rounded-xl border px-3 py-2.5 text-sm"/><input required name="position" placeholder="Position/title" className="rounded-xl border px-3 py-2.5 text-sm"/><input name="department" placeholder="Department" className="rounded-xl border px-3 py-2.5 text-sm"/><select required name="communityId" className="rounded-xl border px-3 py-2.5 text-sm"><option value="">Select community</option>{organization?.communities.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select required name="communityRole" className="rounded-xl border px-3 py-2.5 text-sm"><option value="">Select role</option>{["FACILITY_ADMIN", "PHYSICIAN", "NURSE", "CAREGIVER", "FLEET_MANAGEMENT", "DRIVER"].map((role) => <option key={role} value={role}>{role.replaceAll("_", " ")}</option>)}</select><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Send invitation</button></form></Card>;
  const invitations = <div className="space-y-5">{invitationForm}<Card title="Invitation history" subtitle="Pending invitations expire automatically and can be revoked before acceptance." icon={<Mail className="h-5 w-5"/>}><div className="space-y-2">{organization?.invitations.map((invitation) => <div key={invitation.id} className="flex flex-col gap-2 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-sm">{invitation.email}</b><p className="text-xs text-slate-500">{invitation.community?.name || "Organization-wide"} · {invitation.communityRole || invitation.organizationRole}</p></div><div className="flex items-center gap-2"><Badge value={invitation.status}/>{invitation.status === "PENDING" && <button disabled={busy} onClick={() => void revokeInvitation(invitation.id)} className="rounded-lg border border-rose-200 px-2 py-1 text-xs font-bold text-rose-600">Revoke</button>}</div></div>)}{!organization?.invitations.length && <p className="text-sm text-slate-500">No invitations yet.</p>}</div></Card></div>;

  const approvals = <Card title="Pending staff approvals" subtitle="Approve or reject staff records submitted through delegated facility workflows." icon={<ClipboardCheck className="h-5 w-5"/>}><div className="space-y-2">{pendingStaff.map((staff) => <div key={staff.id} className="flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between"><div><b className="text-sm">{staff.user.name}</b><p className="text-xs text-slate-500">{staff.position} · {staff.community?.name || "Unassigned"} · {staff.user.email}</p></div><div className="flex gap-2"><button disabled={busy} onClick={() => void decideStaff(staff.id, "APPROVED")} className="inline-flex items-center gap-1 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Approve</button><button disabled={busy} onClick={() => void decideStaff(staff.id, "REJECTED")} className="inline-flex items-center gap-1 rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700"><XCircle className="h-4 w-4"/>Reject</button></div></div>)}{!pendingStaff.length && <p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">No staff records are waiting for approval.</p>}</div></Card>;

  const plan = organization?.subscription?.plan;
  const subscription = <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Stat label={`Communities / ${plan?.maxCommunities ?? "∞"}`} value={organization?.communities.filter((item) => item.isActive).length || 0} icon={<Building2 className="h-5 w-5"/>}/><Stat label={`Residents / ${plan?.maxActiveResidents ?? "∞"}`} value={totals.residents} icon={<Activity className="h-5 w-5"/>}/><Stat label={`Staff / ${plan?.maxStaffSeats ?? "∞"}`} value={totals.staff} icon={<Users className="h-5 w-5"/>}/></div><Card title="Subscription" subtitle="Plan changes are handled by the SLMS Platform Administrator." icon={<Gauge className="h-5 w-5"/>}><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div><b>{plan?.name || "No plan assigned"}</b><p className="text-xs text-slate-500">{plan?.key} · {plan?.entitlements.filter((item) => item.enabled).length || 0} enabled module entitlements</p></div><Badge value={organization?.subscription?.status || "UNASSIGNED"}/></div></Card></div>;

  const branding = <Card title="Organization branding" subtitle="These values apply across authorized organization and community experiences." icon={<Palette className="h-5 w-5"/>}><form onSubmit={saveBranding} className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Logo URL<input name="logoUrl" defaultValue={organization?.logoUrl || ""} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-medium">Email sender name<input name="emailFromName" defaultValue={organization?.emailFromName || organization?.name || ""} className="mt-2 w-full rounded-xl border px-3 py-2.5"/></label><label className="text-sm font-medium">Primary color<input name="primaryColor" type="color" defaultValue={organization?.primaryColor || "#2563eb"} className="mt-2 h-11 w-full rounded-xl border p-1"/></label><label className="text-sm font-medium">Secondary color<input name="secondaryColor" type="color" defaultValue={organization?.secondaryColor || "#4f46e5"} className="mt-2 h-11 w-full rounded-xl border p-1"/></label><button disabled={busy} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white sm:col-span-2">Save branding</button></form></Card>;
  const audit = <Card title="Organization audit" subtitle="Sensitive operational actions recorded for this customer tenant." icon={<Shield className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Time</th><th className="p-3">Actor</th><th className="p-3">Action</th><th className="p-3">Target</th><th className="p-3">Reason</th></tr></thead><tbody>{auditEvents.map((event) => <tr key={event.id} className="border-b last:border-0"><td className="p-3 text-xs">{new Date(event.createdAt).toLocaleString()}</td><td className="p-3"><b className="block">{event.actorName}</b><span className="text-xs text-slate-500">{event.actorRole}</span></td><td className="p-3">{event.action}</td><td className="p-3">{event.entityType}</td><td className="p-3 text-xs text-slate-500">{event.reason || "—"}</td></tr>)}</tbody></table></div></Card>;

  const views: Record<string, ReactNode> = { dashboard: overview, communities, people, approvals, invitations, subscription, branding, audit };
  return <div className="space-y-6"><section className="rounded-2xl bg-gradient-to-r from-blue-700 to-indigo-700 p-5 text-white shadow-lg"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-100">SLMS Customer Administration</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{organization?.name || "Organization Admin Portal"}</h1><p className="mt-2 text-sm text-blue-100">Manage communities, people, invitations, access, subscription usage, branding, and tenant security.</p></div>{loading && <Loader2 className="h-5 w-5 animate-spin"/>}</div></section>{error && <div className="flex flex-col gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 sm:flex-row sm:items-center sm:justify-between"><span>{error}</span><button onClick={() => void load()} className="inline-flex items-center justify-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4"/>Retry</button></div>}{organization ? views[tab] || overview : !loading && !error ? <p className="text-sm text-slate-500">Organization data is unavailable.</p> : null}</div>;
}
